### ISSUE TITLE
compare 2 cells after change in any cell value

### ISSUE THREAD

**Issue by gargri** [paulhodel/jexcel#1115]
when we get data dynamically, how we can compare two cell of same row

**Comment by pphod** [comment]
You can compare any piece of data by:
var value1 = table.options.data[y][x]; // Define coords for the first value
var value2 = table.options.data[y][x]; // Define coords for the second value

if (value1 == value2) {
// equal
} else {
// not equal
}

**Comment by gargri** [comment]
where we will have to use it(in which function )

**Comment by pphod** [comment]
you can use any time you want. This is a variable you can have access outside jexcel.
