### ISSUE TITLE
send jexcel data to database

### ISSUE THREAD

**Issue by gargri** [paulhodel/jexcel#1116]
how i can send jexcel data to data base

**Comment by pphod** [comment]
If you start your table with
persistance: 'your-server-url'

Each data change will be submitted to the server. But, you need a backend to support that.

Alternatively, you will be able to use Jexcel Cloud (which will be released in the next few days). Jexcel Cloud is a backend service which you can persist the data of your spreadsheet without worrying about the server, backups etc.
