### ISSUE TITLE
calendar cell - manual date entry return NaN

### ISSUE THREAD

**Issue by morgunder** [paulhodel/jexcel#134]
any tips on manually entering dates?  when we try we get NaN.  thx

![image](https://user-images.githubusercontent.com/3998336/39460939-5518a72a-4cd5-11e8-8654-fb6d53a228ab.png)

**Comment by pphod** [comment]
Please, sync to the master repo and try again.
This was dependent to another lib, but it has a stand-alone implementation in the current version and this should be fixed now.

**Comment by morgunder** [comment]
@paulhodel thank you.  will give the new version a try.
