### ISSUE TITLE
Pasting a large amount of data into a small table causes the page to become unresponsive

### ISSUE THREAD

**Issue by Dadadah** [paulhodel/jexcel#1440]
Pasting a large amount of data into a small table causes the page to become unresponsive. I have been able to reproduce this issue, and have included a reproduction guide.

When a large amount of data is pasted into an empty (or near empty) spreadsheet the library will attempt to add rows and/or columns one at a time. This causes a style update every time a new row or column is added. By making the library insert rows and/or columns before looping through and setting the cells the row and/or columns can be bulk inserted, greatly reducing processing time for pasting.

Reproduction steps:

1. Have a new spreadsheet that has a few columns and rows (like 10 rows and 5 columns).
2. Create a large amount of data that consists of 1000+ rows on a different spreadsheet.
3. Copy said data and paste it into the new spreadsheet.

This operation can take upwards of 30 seconds on modern machines.

I am experiencing this in a production environment. I have also done a profile to confirm this was the issue. I have attached the profile.

![image (1)](https://user-images.githubusercontent.com/22386163/133529358-e982eba5-c728-4336-9f56-98d9a59f1e92.png)

I simulated a potential fix in my onbeforepaste code by parsing the pasted data, counting needed rows and columns and adding them all before pasting.

![image](https://user-images.githubusercontent.com/22386163/133529217-57ed43a2-4ab1-4269-94df-eb06bdb8712f.png)

I can submit a fix for this issue as soon as tomorrow.

**Comment by GBonnaire** [comment]
Hi,

Ok you have some options availables :
Try : `lazyLoading : true, tableOverflow: true,` to create only rows showed

Or try to change function `onbeforepaste` : example here https://github.com/jspreadsheet/ce/issues/1311#issuecomment-780543600

Or use Pro version who have the possibility to manage big data range

**Comment by hodeware** [comment]
You can use lazyLoading or pagination features. That will definitely help a lot since it will create a viewport and limits the number of DOM on your screen at the same time.

But, if you are looking for performance, I would suggest you try the new Version 8. Copy a lot of rows and paste it on this page.
https://jspreadsheet.com/v8/docs/performance

**Comment by Dadadah** [comment]
If anyone else has this issue, this is how I fixed it in my onbeforepaste hook.

```
onbeforepaste: function(instance, clipboard, x, y) {
    // bulk insert columns and rows if needed
    let data = this.parseCSV(clipboard, "\t")
    if (data != undefined && data.length > 0 && data[0].length > 0) {
        let colsNeeded = parseInt(x) + data[0].length - this.headers.length
        if (colsNeeded > 0) {
            this.insertColumn(colsNeeded)
        }
        let rowsNeeded = parseInt(y) + data.length - this.rows.length
        if (rowsNeeded > 0) {
            this.insertRow(rowsNeeded)
        }
    }
},
```
