### ISSUE TITLE
Row header

### ISSUE THREAD

**Issue by syntaxgirl** [paulhodel/jexcel#1448]
Hi, I need to create a header (not changing A,B,C...), but adding a row as a header bellow the columns. They need to be edited as well and I need it to be sticky. Is this possible? 

Also is it possible to have metadata for all fields, so I can save the spreadsheet in database but not in a json format...?

**Comment by GBonnaire** [comment]
Hi,

For your first question, you have nestedHeader, you can look that in this page : https://bossanova.uk/jspreadsheet/v4/examples/nested-headers 
If that isn't that, can you explain with image ?

for your second question, you have meta for cell : you can look that in this page : https://bossanova.uk/jspreadsheet/v4/examples/meta-information
If you use persistence property, you can defined onbeforesave in property for add metadata in data sended to your server

if you use pro version, it's the same behavior.

**Comment by syntaxgirl** [comment]
@GBonnaire 
Something like this?
![image](https://user-images.githubusercontent.com/57375816/136308088-6fdf5bfa-1011-4010-bcb4-40adc6ba9f37.png)

For the second issue with meta, is it possible to get full data with meta data? Because when I try with `jexcel.getJson()` I only get data without meta data

**Comment by GBonnaire** [comment]
Hi,

You can `insertRow` with style and/or add class for first row with `position:sticky;top: 0;` but with this configuration, when you get data/json you have a row header on your data.

I will add in new post (today) several example for add this row

currently no, you need to merge informations from getJson and getMeta

**Comment by GBonnaire** [comment]
Example here for header system like you want : https://jsfiddle.net/guillaumebonnaire/6qkedu0y/21/
