### ISSUE TITLE
Jexcel column filters and search option not working if there are multiple pages

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [paulhodel/jexcel#1450]
Hi,

In my jexcel table there are more than 100 rows. So there are multiple pages created using pagination. So there are 2 problems happening in this situation.
1) When I try to search a value using jexcel column filters it's not working if there are multiple pages
2) One of my column is of type numeric and I am showing the values comma separated. But in column filters the data is not coming comma separated.

**Comment by anchal-chouvhan-altius** [comment]
![comma](https://user-images.githubusercontent.com/55992628/135903491-f05119f3-81da-4529-bb74-e90899d708ef.png)
![filter](https://user-images.githubusercontent.com/55992628/135903498-ddce03a2-8e7d-48d0-9264-3c4cd84c6ab6.png)
![page](https://user-images.githubusercontent.com/55992628/135903506-e82527a4-855e-4000-816b-2a081e4bb431.png)

**Comment by GBonnaire** [comment]
With your screen, i suppose than you use pro version ? if true : i suggest to open this issue on https://github.com/jspreadsheet/pro/issues

I know filter have improved with last version, check if you have last version. If you have always a problem, open new issue on page suggested

@hodeware FYI

**Comment by hodeware** [comment]
We will try that soon and get back to you. Which version are you using?

**Comment by anchal-chouvhan-altius** [comment]
We are using jexcel-pro 7.9.3 version.

**Comment by hodeware** [comment]
Please update to 7.12.2
npm install jspreadsheet-pro
