### ISSUE TITLE
Feature requrest: lazy loading merged cells

### ISSUE THREAD

**Issue by sallyx** [paulhodel/jexcel#1451]
Could you add support for lazy loading json objects in form:
{
data : [...],
mergeCells: [...].
}
or something like that....

**Comment by GBonnaire** [comment]
Hi,

you have an option for lazyloading : you can look an example on this page : https://bossanova.uk/jspreadsheet/v4/examples/lazy-loading

on version pro, lazyloading have improved and manage merges cells

**Comment by sallyx** [comment]
Ok, I didnt know its in pro version only.

**Comment by GBonnaire** [comment]
you have lazyloading on CE version, but it's simple version of the lazy loading

**Comment by sallyx** [comment]
Thanks, I know about the lazy loading. I didnt know that only pro version manages merging cells. (And I dont even see how to do it in pro version.)

**Comment by hodeware** [comment]
A running example:
https://jspreadsheet.com/v8/docs/merged-cells

**Comment by sallyx** [comment]
> A running example: https://jspreadsheet.com/v8/docs/merged-cells

This mreged cells are not defined by lazy loaded data.

**Comment by hodeware** [comment]
There only two ways to merge the data, this one or programmatically applying setMerge('A1', 2, 2); // rowspan colspan.

**Comment by sallyx** [comment]
Thats why I created this feature request.

**Comment by hodeware** [comment]
I am really not sure what do you meant in your comments.

"This mreged cells are not defined by lazy loaded data."

The merge cells are a property applied to the table, that can only be used together with the lazyloading from version 8 using. This particular feature won't be included in any of the previous versions.

**Comment by sallyx** [comment]
OK, I finally found where is the problem: https://jspreadsheet.com/v8/docs/performance "The lazy loading is deprecated, and as a replacement, there is a smart DOM management that will create and show DOM elements on-demand as the user navigates in the viewport." That makes my feature request pointless.

**Comment by hodeware** [comment]
Viewport has the same purpose of lazyloading. And on version 8, you can use this feature with merged cells as you suggested in the initial post.
