### ISSUE TITLE
Date formatting error

### ISSUE THREAD

**Issue by TheJotne** [paulhodel/jexcel#1452]
Hello,

so I used the example from the hompage and changed the date to 2020 and 2021 and it seems that the format is broken after that change.
https://codepen.io/thejotne/pen/qBXadvE

As in the example code the used version is Jspreadsheet 4 and Jsuites 4.

Another problem I found in the given example was the sorting by numbers. It seems that sorting happens based on alphabet and not numeric sorting.

Thank you in advance for taking time to look over the problem

**Comment by hodeware** [comment]
The data problem has been fixed.

**Comment by hodeware** [comment]
Would you mind to open another issue about the sorting.

**Comment by TheJotne** [comment]
No Problem I will open a new issue. Thank you for fixing the error
