### ISSUE TITLE
Number sorting problem

### ISSUE THREAD

**Issue by TheJotne** [paulhodel/jexcel#1453]
Hello,

I took the example from the homepage and changed a few values in the given data.
https://codepen.io/thejotne/pen/qBXadvE

It seems to me that my given numbers are sorted by alphabetic order and not by numbering order. The link will show my tested example.

**Comment by GBonnaire** [comment]
Hi,

Use type number in column properties  instead of type numeric

**Comment by TheJotne** [comment]
Thanks, this seems to work. I was just confused because of the example that was provided at the homepage
