### ISSUE TITLE
Trigger deletion of column

### ISSUE THREAD

**Issue by syntaxgirl** [paulhodel/jexcel#1454]
Hi, I know it's possible to delete column with right click. Is there a way to trigger removing of column with event? I have found 

```
myTable.deleteColumn([integer], [integer]);
```
But, how to figure out on which column I have clicked?

**Comment by GBonnaire** [comment]
Hi,

You have a fonction `jspreadsheet.current.getSelectedColumns()` or the coords of range selected on `jspreadsheet.current.selectedCell`

Try this. But, it’s possible there is a better method for your bahovior requested

**Comment by hodeware** [comment]
you have the information onbeforedeletecolumn or ondeletecolumn
