### ISSUE TITLE
Copy paste of header multilevel

### ISSUE THREAD

**Issue by assadi** [paulhodel/jexcel#1455]
I'm using spreadsheet v8 to render worksheets on html. I have nested headers on my tables and I'm trying to enable including the table header on copy/paste. I'm using the configs: // @type {boolean} - Include the header titles on download includeHeadersOnDownload:false, // @type {boolean} - Include the header titles on copy includeHeadersOnCopy:false,  It appears that they work only for the first level of the header.

**Comment by hodeware** [comment]
Yes, it works only for the headers. But, you can implement additional actions using onbeforepaste and onpaste to create a behavior as intentend.
