### ISSUE TITLE
Error on multiple dropdown

### ISSUE THREAD

**Issue by arifinoid** [paulhodel/jexcel#1456]
facing error when define column type of dropdown
![Screen Shot 2021-11-03 at 15 41 00](https://user-images.githubusercontent.com/48134691/140030734-b08898a1-4fec-4ec5-bc50-f105c960aa69.png)
the column is like this one:
![Screen Shot 2021-11-03 at 15 41 51](https://user-images.githubusercontent.com/48134691/140030781-54fe7a8d-c006-4684-bd2a-d8f9014c1c4a.png)
please help @pphod  thank you

**Comment by GBonnaire** [comment]
Hi,

Can you tell me your version of jspreadsheet ?

And just for information, in value in source in index 1, do you have try without emoticon ?

**Comment by arifinoid** [comment]
@GBonnaire 4.9.5, that problems already solved, I just made a mistake, but I'm facing another problem rn, how can we get the info/metadata file from the image, because after we insert the image into the sheet, we immediately get base64 data??

**Comment by GBonnaire** [comment]
Hi,

On editor image, you have only base64 on value. But this editor use jSuites.image and on edition, you can get meta in `content` property.

The easier way is create custom editor based on editor image and on close, get meta value on `content` property of div :

`jSuites.image(div, options);`

after import :
`div.content` contains all informations of file

**Comment by arifinoid** [comment]
thank you for reply @GBonnaire, i will try it. One more question sorry, suppose we have many column that overflow-y the container, how to keep the focus / highlighted cell in monitor instead of using mouse, but using our arrow key on keyboard so the user no need to scroll it using mouse, so it will be the same as google sheet behaviour like this image:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48134691/140927310-fab564d5-5e05-499d-b99c-a03d82b137f7.gif)

**Comment by GBonnaire** [comment]
This behavior work by default with option tableOverflow : https://bossanova.uk/jspreadsheet/v4/examples/table-overflow

If you want give focus on load, you need select cell on onload function

**Comment by arifinoid** [comment]
thank you @GBonnaire it works, issue closed
