### ISSUE TITLE
Show progress bar while downloading?

### ISSUE THREAD

**Issue by abuhasnatchow** [paulhodel/jexcel#1460]
Hello Sir
Is their a way to show progress bar while downloading to csv?
Thanks in advance

**Comment by GBonnaire** [comment]
On version CE no, you need override function for set states and progression and after you can show progress bar with this component : https://github.com/jsuites/jsuites/tree/master/packages/progress

**Comment by abuhasnatchow** [comment]
Thank you very much for your reply.
