### ISSUE TITLE
Enable header selection

### ISSUE THREAD

**Issue by assadi** [paulhodel/jexcel#1461]
Today, If we want to selct, copy data from table and paste it to excel we can update the property includeHeadersOnCopy that will automatically copy the header when copying couple of cells. So either with header or without. 
Can we enable header selection via mouse so the header will be included in the selection rectangle?

**Comment by GBonnaire** [comment]
Currently, you can click on header for select full column. After on event onbeforecopy you can defined, if column is full selected you add header

The better solution : use contextmenu on header and add item copy with header et create your own function copy
