### ISSUE TITLE
Allow edit width of column of row titles

### ISSUE THREAD

**Issue by jonathanyu1** [paulhodel/jexcel#1462]
I was wondering if there is any way of editing the width of the column that holds all the row titles (in the example below, 'Wk 1'...)

https://i.imgur.com/0vsUGCZ.png

**Comment by hodeware** [comment]
You can change using CSS, but you might end up with unexpected behavior with you are using freezeColumns.

**Comment by jonathanyu1** [comment]
How can you directly reference that specific column? I dont see anything in the documentation
