### ISSUE TITLE
How to make index resizable?

### ISSUE THREAD

**Issue by kpagcha** [paulhodel/jexcel#1465]
I have a mirrored table where column headers are the same than row headers (index). I'm labelling them as follows (as opposed to showing the index number):

```
Array.from(spreadsheet.el.getElementsByClassName('jexcel_row')).forEach((rowHeader, i) => {
    rowHeader.innerText = rowHeader.title = venueData[i].name;
});
```

(I really wish row headers were a feature by the way)

However, depending on how long the text is, the column might not be wide enough. I tried setting the `columnResize` option (which is `true` by default) and it works great on data columns, but it turns out it cannot be used with the very first column: the index.

How could I do that?

(Adjusting the column width to the text is not an option)

**Comment by GBonnaire** [comment]
You can't resize like other column first column with Index.

If you want change width, you need change value on colgroup > first col width
