### ISSUE TITLE
Question: links handling with Free or Pro license

### ISSUE THREAD

**Issue by monica123m** [paulhodel/jexcel#1466]
Hello, i'm actually using the free JSpreadsheet version [v4] . 
I noticed that every <a> tag in my html tables are parsed as strings. 

I was wondering if links can be managed in the free version or if they are in the PRO version. 

i'd like to obtain a column with clickable words, to navigate to other pages.

Thank you very much.

**Comment by hodeware** [comment]
I believe you would like some sort of custom editor, It means an action added to the cell as the example below:
https://jspreadsheet.com/v7/examples/remote-database-record-ids

**Comment by monica123m** [comment]
Hi, i wrote my custom js in the end to reach the result, thank you
