### ISSUE TITLE
component does not update after fetch request

### ISSUE THREAD

**Issue by JmiXIII** [paulhodel/jexcel#1468]
trying to update Vuejs3 component jspreadsheet-ce (excellent js library) with fastpi request. Vue component does not update whereas data seems to update correctly.

FastAPI main.py extract :

@app.get("/rr/")
async def create_rr():
    return {"data" : [[1,1,5.25], [2,1,5.26], [3,1,5.27],[3,1,5.27],[3,1,5.27]]}

App.vue

<template>
  <VueJSpreadsheet v-model="dataTable" :options="myOption" id="table" />
  data check {{ dataTable }}
</template>

    <script>
    import VueJSpreadsheet from "vue3_jspreadsheet";
    import { ref } from "vue";
    
    export default {
      components: {
        VueJSpreadsheet,
      },
      data() {
        const dataTable = ref([[1], [2], [3]]);
    
        return {
          dataTable,
        };
      },
      created: async function () {
        const rrResponse = await fetch("http://localhost:8000/rr");
        const rrObject = await rrResponse.json();
        this.dataTable = ref(rrObject.data);
        console.log(this.dataTable);
      },
    };
    </script>

{{dataTable}} update corretly but not I do not understand why component does not.

**Comment by hodeware** [comment]
You need to call instance.setData(yourFechedData)

**Comment by JmiXIII** [comment]
was a vue3_jspreadsheet issue => solved thansk to killkli

https://github.com/killkli/vue3_jspreadsheet/issues/2

Suggest to document this component !
