### ISSUE TITLE
Access child objects' properties

### ISSUE THREAD

**Issue by Scrandre** [paulhodel/jexcel#1470]
There is a good example of how it can be implemented (the object is flattened with its name transformed into a full property path):
https://www.convertjson.com/json-to-html-table.htm
Then on getJSON() it can be reassembled back

**Comment by hodeware** [comment]
I am not sure what is the question.

**Comment by Scrandre** [comment]
If there is a child object it's is not expanded into separate accessible fields:
```
parent: {
  child: {
    property1: "foo",
    property2: "bar"
}
```
The parent object can be flattened and the columns can be accessed in the "parent/child/property1"-like style

**Comment by Scrandre** [comment]
Can the issue be reopened? I didn't have an opportunity to provide details
