### ISSUE TITLE
how to create dynamic tables using jexcel

### ISSUE THREAD

**Issue by kallaguntaashok** [paulhodel/jexcel#1471]
i used jexcel for static columns, what if I want to add Column's dynamically based on user selection.

See below image left side assume we have jexcel table right side box has columns, based on column selection is it possible to load "columns" selection in jexcel. 

columns: [
        {
            type: 'dropdown',
            url:'https://bossanova.uk/jspreadsheet/v4/countries',
            width:200,
        } ]

does above code section support JSON object data binding for columns block ?
or is there a way to load this column config dynamically. 

![image](https://user-images.githubusercontent.com/26366259/143789405-b9818b89-aba4-4703-8459-e6c38e8f32dd.png)

**Comment by hodeware** [comment]
You can use insertColumn to create columns dynamically. Or simple hide/show some pre loaded ones.
