### ISSUE TITLE
jexcel.js:11133 Self Reference detected

### ISSUE THREAD

**Issue by Hatelace** [paulhodel/jexcel#1473]
<html>
      <script src="https://bossanova.uk/jspreadsheet/v4/jexcel.js"></script>
      <script src="https://jsuites.net/v4/jsuites.js"></script>
      <link
        rel="stylesheet"
        href="https://jsuites.net/v4/jsuites.css"
        type="text/css"
      />
      <link
        rel="stylesheet"
        href="https://bossanova.uk/jspreadsheet/v4/jexcel.css"
        type="text/css"
      />
  
    <div id="spreadsheet"></div>
  
    <script>
      var data = [
        ["Cheese", 10, 6.0, "=B1*C1"],
        ["Apples", 5, 4.0, "=B2*C2"],
        ["Carrots", 5, 1.0, "=B3*C3"],
        ["Oranges", 6, 2.0, "=B4*C4"],
      ];
  
      var table = jspreadsheet(document.getElementById("spreadsheet"), {
        data: data,
        footers: [['=A1', '=SUM(B1:B4)', '=C1', '=D1']],
        defaultColWidth: 200,
      });
      </script>
    </html>
   
I am getting #ERROR in footer. Why? And what am I doing wrong?
In console "Self Reference detected"

**Comment by GBonnaire** [comment]
I have make a PR to fix your issue : https://github.com/jspreadsheet/ce/pull/1476
