### ISSUE TITLE
Access child objects' properties

### ISSUE THREAD

**Issue by Scrandre** [paulhodel/jexcel#1477]
If there is a child object it's is not expanded into separate accessible fields:

```
parent: {
  child: {
    property1: "foo",
    property2: "bar"
}
```
The parent object can be flattened and the columns can be accessed in the "parent/child/property1"-like style

There is a good example of how it can be implemented (the object is flattened with its name transformed into a full property path):
https://www.convertjson.com/json-to-html-table.htm
Then on getJSON() it can be reassembled back

**Comment by hodeware** [comment]
This turn more complex when you start to create new columns, new rows, etc.

But, that is available on the PRO version.
https://www.jspreadsheet.com/v8/docs/data

We don't have expectations to bring that to the CE version. If you wish, fell free to send a PR.
