### ISSUE TITLE
when insert new row I want add fomula in new row's readonly cell

### ISSUE THREAD

**Issue by didi9417** [paulhodel/jexcel#1481]
I found readonly cell can't set fomula when insert new row

so I was try edit JexcelV4.js but I didn't solve

I don't know how to solve this problem

**Comment by GBonnaire** [comment]
Hi,

Do you have try with argument force = true ?

```javascript
MyTable.setValue("A1", "=SUM(1,2)", true);
```

**Comment by didi9417** [comment]
Thank you! GBonnaire :)
I didn't know there was a force attribute 
so I was remove read-only property on readonly cell 
and set value and add read-only property 
thanks!! :)
