### ISSUE TITLE
How can I set the position of tabs?

### ISSUE THREAD

**Issue by TheaWu7** [paulhodel/jexcel#1485]
tabs always on the top
![image](https://user-images.githubusercontent.com/91300914/146121047-553e66a9-4835-4b9d-9230-92e222e22a1b.png)
how can I set it's position to make it fixed to the bottom like excel
![image](https://user-images.githubusercontent.com/91300914/146120778-90edff6a-141c-4c78-84f4-b8e0c59841b0.png)

**Comment by GBonnaire** [comment]
On version CE you need to use your external javascript for make this changement. On JSS v8 is easier.

On CE you can get DOMElement of tabs like this
```
// From Div of JSS when you create JSS
if(DivOfJSS.classList.contains("jexcel_tabs")) {
   var tabs = DivOfJSS.children[0];
}

// From instance
var DivOfJSS = MyTable.el.parentNode.parentNode;
if(DivOfJSS.classList.contains("jexcel_tabs")) {
   var tabs = DivOfJSS.children[0];
}
```

After you need change position, like style position:fixed;bottom:0 for example

**Comment by dmt0** [comment]
So how do you do it in v8?

**Comment by GBonnaire** [comment]
Hi

About JSS Pro v8, you can use this :

```javascript
jspreadsheet(document.getElementById('spreadsheet'), {
    /* your global conf */
    tabs: {
          position: "bottom",
    },
    worksheets: [{
        minDimensions: [8,8],
        /* your conf worksheet */
    }],
});
```

Have good day 😉
