### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by phuze** [paulhodel/jexcel#1488]
I am trying to support multiple languages.

I've managed to partially achieve this by using the `setHeader()` method.
However, this doesn't apply to **nested headers**, or **footers**.

How can I update nested header and footer values programmatically?

Also, just to confirm, jspreadsheet does not internally support internationalization, is that correct?

**Comment by GBonnaire** [comment]
Hi,

you have in options of jspreadsheet instance, a property "text" and you can defined all text from this :

You can found some example here : https://github.com/jspreadsheet/ce/tree/master/lang

And if you want, you can use` jSuites.translate("my text") ` and defined translation before with `jSuites.setDictionnary({"my text":"my translation", "my text 2":"my translation 2"};`

And example for title of column with translation :
```javascript
columns: [
  {title: jSuites.translate("My title"), width: 120}
],
```
