### ISSUE TITLE
argument of type error in angular 

### ISSUE THREAD

**Issue by kallaguntaashok** [paulhodel/jexcel#1490]
![image](https://user-images.githubusercontent.com/26366259/147016260-64667a18-d36b-4166-9b3d-8b9b77edceee.png)

first time, I am going to use jspreadsheet in angular, I am surprised seeing this error in basic example that you have given in the portal.

Could you please tell me what went wrong. 

I am planning to purchase Jspreadsheet pro, is your code support angular?

**Comment by GBonnaire** [comment]
Hi,

try to remove this line and let jspreadsheet defined by default this value :
`data:[[]],`

you can use to defined dimension of table : 
`minDimensions: [5,5],`

**Comment by hodeware** [comment]
That was resolved.
