### ISSUE TITLE
After deleting rows, the subsequent row title becomes the row number.

### ISSUE THREAD

**Issue by luncheon** [paulhodel/jexcel#1494]
(I'm sorry to be rude, but I'm not good at English.)

If `obj.options.rows[j].title` exists, it should be used.
https://github.com/jspreadsheet/ce/blob/a8acbdba8159c5395eeb391ae8df23892568c636/src/index.js#L4767

**Comment by GBonnaire** [comment]
Yes, it's true. Could you create a PR with fix ?

**Comment by luncheon** [comment]
Thank you but I don't know how to build `dist/index.js` correctly and how to run tests...
(When I type `docker-compose up packages` and `docker-compose up transpile` on my mac, I get many diffs of `dist/index.js`)

**Comment by GBonnaire** [comment]
You improve the file in `src` 😉  and after when author compiled file, recompiled this fix 😊
