### ISSUE TITLE
 I want to know how to reset the filtered row

### ISSUE THREAD

**Issue by didi9417** [paulhodel/jexcel#1496]
Hello,
I want to know how to reset the filtered row
I was used  obj.resetFilters(), obj.closeFilter(), obj.filter = null; obj.filters = [];
but It doesn't work.... 
Is it have any function for reset the filtered row in jexcelV4?

**Comment by hodeware** [comment]
That has been fixed. v4.9.11+

**Comment by didi9417** [comment]
use resetFilters(), resetSelection(), resetSearch()
