### ISSUE TITLE
text-wrap cell's shape control

### ISSUE THREAD

**Issue by didi9417** [paulhodel/jexcel#1497]
Hello and thanks for this amazing library.

I want all rows to have the same height regardless of text-wrap attribute
Is there a way to make cell spread when double-clicked like ms excel?

![2](https://user-images.githubusercontent.com/89561822/150083905-ec328aa4-351d-4957-9e0e-29cce04e7787.PNG)

**Comment by GBonnaire** [comment]
Could you precise your question ?

Do you search cell have a overflow text ? or editor ? or editor is contained in cell without overflow ?

i think only with CSS (text-overflow or overflow-x or overflow-y) you can make the behavior expected 😉
