### ISSUE TITLE
Is there only decimal masks?

### ISSUE THREAD

**Issue by gabrielmandel** [paulhodel/jexcel#1499]
It would be nice for me, in my actual project to use mask in this SpreadSheet but i need mask 2 columns with "00000" (if i have a number the value would be "00012" or "00862", etc), but everything i searched leads to using this mask with currency values

**Comment by GBonnaire** [comment]
Hi,

Sorry mask on jSuites can't make that. And in jSpreadsheet you can't use mask for this.

2 solutions possibles :
- improve jSuites mask to accept this format 00000 (i think is better)
- create a custom editor for show value in this format 00000

Have good day
