### ISSUE TITLE
Documentation source request

### ISSUE THREAD

**Issue by chepo92** [paulhodel/jexcel#1502]
Is it possible to release the source of the [documentation page](https://bossanova.uk/jspreadsheet/v4) under a folder or a separate repository? Some sections and functions need update, also for correcting typos. It may be deployed as github pages or as a read the docs page

 @hodeware (or whoever is maintaining this repo)

**Comment by hodeware** [comment]
https://github.com/jspreadsheet/ce-docs

**Comment by hodeware** [comment]
We are working to improve that. But this is currently how the docs are contructed.

**Comment by chepo92** [comment]
Thank you @hodeware
