### ISSUE TITLE
`getJson` method does not include newly added column header

### ISSUE THREAD

**Issue by stolarczyk** [paulhodel/jexcel#1504]
# How to reproduce

Please use this [JS Fiddle](https://jsfiddle.net/u2g0axnq/36/) to reproduce the behavior: 
1. right click on the column header and select "Insert a new column before" from the context menu
2. right click on the newly added column and select "Rename this column" from the context menu. Name it `"test"`
3. Input some text to the new cells
3. Click "getJSON" button

# Result
```
[{
  0: "a",
  Description: "Test desc 1",
  ID: "first"
}, {
  0: "a",
  Description: "Test desc 2",
  ID: "second"
}]
```
# Expected result
```
[{
  test: "a",
  Description: "Test desc 1",
  ID: "first"
}, {
  test: "a",
  Description: "Test desc 2",
  ID: "second"
}]
```

**Comment by hodeware** [comment]
The property name which defines the key for the JSON is not changed when you change the title. For that you will need to implement something using onchangeheader.
