### ISSUE TITLE
deleteColumn Method taking too much time to execute

### ISSUE THREAD

**Issue by harshvarudkar** [paulhodel/jexcel#1505]
myTable.deleteColumn(7, 1);
![image](https://user-images.githubusercontent.com/12017862/152387496-4e566765-af1e-4ba3-a1fb-df0786a99dbe.png)

**Comment by chepo92** [comment]
maybe more details to reproduce ?

**Comment by hodeware** [comment]
How many rows do you have? Do you have events associated?

**Comment by harshvarudkar** [comment]
> How many rows do you have? Do you have events associated?

10 Rows

**Comment by hodeware** [comment]
That is probably link to any implementation inside events, there is no other reason to explain that and considering no further information was provided I am closing this one.
