### ISSUE TITLE
Scrolling two grids

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1509]
Hi

I need move other grid scroll when  scrolling another grid, It's is possible?

thx!!!

**Comment by ricardoperroni** [comment]
I cant do

$('#grid1 .jexcel_content').scroll(function(e) {
	$('grid2 .jexcel_content').scrollTop($('#grid1 .jexcel_content').scrollTop());
})

$('#grid2.jexcel_content').scroll(function(e) {
	$('grid1 .jexcel_content').scrollTop($('#grid2 .jexcel_content').scrollTop());
})

Thx!

**Comment by GBonnaire** [comment]
Hi,

The better solution it's to sync scrolling with value scrollTop and scrollLeft

You can use addEventListener "scroll" on .jexcel_content and set scrollTop value.

Why you can't do make this with jQuery ?

**Comment by ricardoperroni** [comment]
I did
Thx

**Comment by GBonnaire** [comment]
It's you found a solution. Could you close this issue ? thx

**Comment by ricardoperroni** [comment]
yeap
