### ISSUE TITLE
Correct formula Len

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1510]
Pls, add code 

![image](https://user-images.githubusercontent.com/26558844/154566099-84aa20a4-cc61-43dc-9938-57464937d984.png)

**Comment by GBonnaire** [comment]
Hi,

Could you make a PR?

Thanks

**Comment by ricardoperroni** [comment]
Hi,

Sorry, but, what's PR?....

**Comment by GBonnaire** [comment]
Pull request on Git : 

https://github.com/jspreadsheet/ce/pulls

**Comment by ricardoperroni** [comment]
It's my first time do this.... I can't find file jsexcel.js

**Comment by GBonnaire** [comment]
https://opensource.com/article/19/7/create-pull-request-github

In summary, if you want to contribute to the project, the simplest way is to:
1. Fork it
2. Clone it to your local system
3. Make a new branch
4. Make your changes
5. Push it back to your repo
6. Click the Compare & pull request button
7. Click Create pull request to open a new pull request
