### ISSUE TITLE
Disable editor in cell html

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1515]
Hi

I need disable the editor on double click, it's possible?

Thx

![image](https://user-images.githubusercontent.com/26558844/156223974-6c51fdcc-22c3-4ee7-abab-73f0df0a0aef.png)

**Comment by GBonnaire** [comment]
Hi,

Did you try with option `editable: false,`  ?

**Comment by ricardoperroni** [comment]
Hi,

Add "editable:false", unfortaly doens't work... I need inject select2 component in cell.

**Comment by ricardoperroni** [comment]
For now, I do this.
![image](https://user-images.githubusercontent.com/26558844/158036268-cb0256da-4011-471d-92cd-a7b705a74f15.png)

**Comment by GBonnaire** [comment]
sorry, i don't understand you want make.

In jspreadsheet, you can disable editor with 3 way :
`editable:false,` in configuration of jspreadsheet
`readOnly:true,`in configuration of column
`class="readonly"`add class readonly on td (cell)

**Comment by ricardoperroni** [comment]
I need inject in the cell select2 component, when I search anything in select2, open another editor html.

When readOnly equal true, all events are disabled?

**Comment by GBonnaire** [comment]
I think for your request, you need use custom editor (custom type column). And with that you have the possiblity to create your input (even hidden if you want)

https://bossanova.uk/jspreadsheet/v4/examples/column-types

**Comment by ricardoperroni** [comment]
Like this?
![image](https://user-images.githubusercontent.com/26558844/159711069-083e2905-564b-4cc5-9757-769c1c697131.png)

**Comment by GBonnaire** [comment]
Yes and 

```javascript
var customColumn = {
    // Methods
    closeEditor : function(cell, save) {
        var value = cell.children[0].value;
        cell.innerHTML = value;
        return value;
    },
    openEditor : function(cell) {
        // Create your input and your behavior when user double click on cell
    },
    getValue : function(cell) {
        return cell.innerHTML;
    },
    setValue : function(cell, value) {
        cell.innerHTML = value;
    }
}
```

**Comment by ricardoperroni** [comment]
Work!!

Thx!!!!
