### ISSUE TITLE
DropDown in modal (twitterbootstrap)

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1516]
Hi,

I using jspreadsheet in modal, but,  lost position of dropdown list, 

thx

**Comment by GBonnaire** [comment]
Do you use modal of jSuites ?

**Comment by ricardoperroni** [comment]
No, my project using twitter bootstrap modal.

**Comment by GBonnaire** [comment]
Hi,

I have tried you reproduct this error. But for me it work.

Could you share configuration of jspreadsheet ? and version used

**Comment by ricardoperroni** [comment]
My version is 4.10.1 / twitter bootstrap 4

**Comment by ricardoperroni** [comment]
![image](https://user-images.githubusercontent.com/26558844/159534514-8d9b1f3d-5d8d-4069-85d5-357a7085fb7e.png)

**Comment by GBonnaire** [comment]
Check with your CSS your container, maybe you should use position: relative or fixed in div contain JSS

**Comment by ricardoperroni** [comment]
I changed code below and works, but, I think this is not correct. Another idea?
![image](https://user-images.githubusercontent.com/26558844/196209775-fb78122c-f677-4d37-a95e-375597d7f5fb.png)

**Comment by ricardoperroni** [comment]
I Have other solution, I think its the better.
![image](https://user-images.githubusercontent.com/26558844/196236078-b5564ebb-b6ab-4b11-80df-f8310a420c96.png)
