### ISSUE TITLE
Hide nestedHeaders

### ISSUE THREAD

**Issue by Prit17** [paulhodel/jexcel#1517]
Hello, how we can hide nestedHeaders and show on button click?
Please help...

**Comment by GBonnaire** [comment]
Hi

Each nested is tagged by class .jexcel_nested. With that you can hide/show with this function

```javascript
// For hide
document.querySelectorAll(".jexcel_nested").forEach(function(item) { item.style.display = "none"; });
```

```javascript
// For show
document.querySelectorAll(".jexcel_nested").forEach(function(item) { item.style.display = ""; });
```

if you have multiple document, change selector or document in query 😉
