### ISSUE TITLE
Insert a new row and the merged cells are not refreshed; Error when deleting line

### ISSUE THREAD

**Issue by yanjc39** [paulhodel/jexcel#1518]
![image](https://user-images.githubusercontent.com/33985927/156551532-2c3f5a59-d596-4c6a-b402-ab10169aa696.png)

1.add new row before no.2 row;
2.delete the row that the step 1 inserted;

**Comment by jefersondiasdev** [comment]
Could you give us your code?

**Comment by hodeware** [comment]
If you wish to send more stops for replication we can try to help.
