### ISSUE TITLE
How to sum only filtered rows on footer

### ISSUE THREAD

**Issue by didi9417** [paulhodel/jexcel#1521]
Hi 
Thanks for providing a great library :)
I want to know how to sum only filtered rows on footer When using the filtering

**Comment by GBonnaire** [comment]
Hi,

It’s complex, but you can use custom formula, through in the arguments index of column (A = 0, B = 1, …) and in formula you get all cells of columns, if cell is visible get value otherwith continue next cell.

Try this, (sorry, currently i can’t make an exemple in JS)
