### ISSUE TITLE
Dropdown Muliselect issue

### ISSUE THREAD

**Issue by darshandoshi27** [paulhodel/jexcel#1523]
I am using multi select option for dropdown and I want items to be seprated by comma (",") instead of semicolon (";") during multiselect
can anyone help me out for this ?

**Comment by GBonnaire** [comment]
Hi,

Currently it's no possible to defined separator on dropdown component of jsuites. You need use a custom editor with an other dropdown component

**Comment by hodeware** [comment]
That is not supported in the CE versions.
That is available on the PRO distributions using the { type:'dropdown', options: {divisor: '|' } } for example
