### ISSUE TITLE
Order by Fix

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1525]
Hi
I have problem with the OrderBy function, number columns has a problema. I Fix in my version (4.10.1).

![image](https://user-images.githubusercontent.com/26558844/159530380-1ee7debc-b2b0-479a-b239-c7abe4e22062.png)
Left - Wrong / Right correct.

**Comment by GBonnaire** [comment]
Could you make a Pull request on this git ?

**Comment by gcfalck** [comment]
I was having the same issue. Thx for finding this. Would it make sense to leave "number" so if someone currently uses number, your fix won't break them?
