### ISSUE TITLE
Jexcel cell with an input type: 'image' is opening a browse pop up on click of image

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [paulhodel/jexcel#1526]
Hi,
Jexcel cell with an input type: 'image' is opening a browse pop up on click of image. Can we stop browse pop up from opening?

**Comment by GBonnaire** [comment]
Hi,

set column into property `readOnly: true`

**Comment by anchal-chouvhan-altius** [comment]
It worked.Thank you.
