### ISSUE TITLE
Suspend Events

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1527]
Hi,

How suspend all events spread?

Thx

**Comment by GBonnaire** [comment]
hi,

You have property to ignore all events

In configuration add :
```javascript
var MyTable = jspreadsheet(DOMElement, { 
   /* ... */
   ignoreEvents: true,
}
```
After loaded, you can change this value
`MyTable.options.ignoreEvents = true;`

**Comment by ricardoperroni** [comment]
Thx!!!
