### ISSUE TITLE
Can't I put a formula in a column?

### ISSUE THREAD

**Issue by didi9417** [paulhodel/jexcel#1528]
Hi
Now I'm putting formulas one by one in the rows of the same column

If Can't I put a formula in a column and the formula automatically generated in rows?
Thank you :)

**Comment by GBonnaire** [comment]
Hi,

Do you have try this function :
```javascript
myTable.setColumnData(numberColumn, ArrayOfDatas);
```

Extract of documentation : 
setColumnData: Set the data from one column by number@Param integer columnNumber - Column number@param array colData - Column data | myTable.setColumnData([int], [array]);
