### ISSUE TITLE
Is there any possibility to show the total of items in a table?

### ISSUE THREAD

**Issue by zehguilherme** [paulhodel/jexcel#1530]
For example: this table only shows the number of pages (51) and there are 503 items.

I would like to show this number (503) right next to or below the number of pages.

![image](https://user-images.githubusercontent.com/36301054/161990195-f40d84e9-8476-4cb1-99f9-1e507af3e0ee.png)

**Comment by GBonnaire** [comment]
Hi,

I don't think so.

But, you can override some function like

```javascript
var MyTable = jspreadsheet(DOMElement, { /* options */ });

var parentUpdatePagination = MyTable.updatePagination;
MyTable.updatePagination = function() {
      parentUpdatePagination();
      MyTable.pagination.children[0].innerHTML += " - " + MyTable.rows.length + " item(s)";
}
```
(Code not tested)

**Comment by zehguilherme** [comment]
It worked. I just added it inside a `span` element with a concatenated text at the end.

```html
<span>${table.rows.length} items<\span>
```
