### ISSUE TITLE
Identify whether the cell is blank or 0 in formula

### ISSUE THREAD

**Issue by dolly-chhabriya-altius** [paulhodel/jexcel#1531]
Hi Team,

I want to use formula on cell B2 in such a way that if A2 is blank then B2 should also show blank and if A2 is 0 the it should show 0 otherwise it should show A2/2. Currently it is not differentiating between 0 and blank while using formulas.

**Comment by GBonnaire** [comment]
Hi,

Did you have try with formula : ISBLANK(A1) ?

**Comment by dolly-chhabriya-altius** [comment]
I tried that but it is giving an error. Below is the link for the jsfiddle
https://jsfiddle.net/ncqor65z/

**Comment by GBonnaire** [comment]
It’s on Pro version, could you open ticket directly on github pro version ? 

http://github.com/jspreadsheet/pro

@hodeware Error on V8 Pro 😉

**Comment by dolly-chhabriya-altius** [comment]
Okay. Thank you

**Comment by hodeware** [comment]
There are a new release coming soon for the Formulas Pro which will bring several improviments, including differences null/zero. 

Approx. 3 weeks.
