### ISSUE TITLE
passed Dropdown elements not displaying, but highlighted on clicking 

### ISSUE THREAD

**Issue by Sholls000** [paulhodel/jexcel#1532]
I posted data to my dropdown from an array but the posted data was not being displayed. However, on clicking the affected dropdown(s), the posted data is highlighted, could I be missing something? 
The photo below displays the problem.
![SampleScreen](https://user-images.githubusercontent.com/56219088/163810377-51edaf46-0a69-4280-ad30-9b85f44dd24b.png)

**Comment by GBonnaire** [comment]
Hi,

Could you share a part of your code explained in your post or reproduct problem on JSFiddle ?

and could you precise version of Jspreadsheet and jSuite used on your code ?

Thanks

**Comment by Sholls000** [comment]
You could close this issue, I found a way to resolve the problem...The react useEffect where the pasted table elements were called rendered before the component calling the table. Fixed it by making the table render first before pasting the data.
