### ISSUE TITLE
Multiple Cell Selection Drag and Drop with Formulas 

### ISSUE THREAD

**Issue by timinho111** [paulhodel/jexcel#1533]
Hi,

first off congrats on this great project. I really enjoy working with Jspreadsheet and it has a great use case in my project.

There is one use case I have which is not doable with Jspreadsheet. I also checked the pro version on jspreadsheet.com and it also does not feature it.

It's about the following behavior which can be done in excel:

When I have a formula in a single cell and drag it down it correctly auto increments. It works in Jspreadsheet also up/down and left/right.
![Bildschirmfoto 2022-04-20 um 12 00 16](https://user-images.githubusercontent.com/28393814/164203494-628701e1-af95-4908-8a3b-cb55141c06fc.png)

When I now select this row with relative formulas and drag them to the right, in excel they get auto incremented and reflect the relative cell relation for all of those cells:
![Bildschirmfoto 2022-04-20 um 12 02 24](https://user-images.githubusercontent.com/28393814/164203871-8f289a1a-628d-4b5a-bfad-5fd312970d6f.png)
![Bildschirmfoto 2022-04-20 um 12 00 38](https://user-images.githubusercontent.com/28393814/164203592-7d2e20c0-f08c-4ee0-9ff5-a2d7c73e5ebc.png)

Is there a plan to also support this? For me this would be a much needed feature. 

BR
Tim

**Comment by GBonnaire** [comment]
@hodeware : feature for next pro version ?

**Comment by hodeware** [comment]
Yes, that has been included on PRO Version 9+
