### ISSUE TITLE
Display different dropdown values based on a hidden column when jexcel table is rendered

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [paulhodel/jexcel#1534]
Hi,

I want to display different dropdown values in a column. I have a hidden column based on which I want to display these values when the table is rendered .

**Comment by GBonnaire** [comment]
Hi,

You can use dropdown conditionnal

Example :

```HTML
<div id="spreadsheet2"></div>
 
<script>
var data2 = [
    [3, 'Cheese', true],
    [1, 'Apples', true],
    [2, 'Carrots', true],
    [1, 'Oranges', false],
];
 
dropdownFilter = function(instance, cell, c, r, source) {
    var value = instance.jexcel.getValueFromCoords(c - 1, r);
    if (value == 1) {
        return ['Apples','Bananas','Oranges'];
    } else if (value == 2) {
        return ['Carrots'];
    } else {
        return source;
    }
}
 
jspreadsheet(document.getElementById('spreadsheet2'), {
    data:data2,
    columns: [
        { type:'dropdown', title:'Category', width:'300', source:[ {'id':'1', 'name':'Fruits'}, {'id':'2', 'name':'Legumes'}, {'id':'3', 'name':'General Food'} ] },
        { type:'dropdown', title:'Food', width:'200', source:['Apples','Bananas','Carrots','Oranges','Cheese'], filter:dropdownFilter },
        { type: 'checkbox', title:'Buy', width:'100' },
    ],
    onchange:function(instance, cell, c, r, value) {
        if (c == 0) {
            var columnName = jspreadsheet.getColumnNameFromId([c + 1, r]);
            instance.jexcel.setValue(columnName, '');
        }
    }
});
</script>
```

More information on this page : https://bossanova.uk/jspreadsheet/v4/examples/dropdown-and-autocomplete

**Comment by anchal-chouvhan-altius** [comment]
Thank you.
[image: altius_logo] <http://www.altius.cc/>


Anchal ChauhanProject Lead+919637139638 | ***@***.***
***@***.***> | 0712 2464000 Extn 23
3rd Floor, North & South, B Wing, Central Facility Building, MIHAN SEZ
Area, Nagpur - 441108.
Locations: Mumbai | Nagpur | Pune | Dubai | Dallas


[image: WHRDC_logo]
<https://s3.ap-south-1.amazonaws.com/altius.cc/email_signature/World_HRD_Congress_Certificate.jpg>
 [image: CRISIL_logo]
<https://www.crisil.com/ratings/nsic-rating-list.jsp> [image:
15_Innovation_logo] <http://www.altius.cc/>
Follow Us:
[image: facebook_logo] <https://www.facebook.com/altiuscustservices/> [image:
linkedin_logo]
<https://in.linkedin.com/company/altius-customer-services-pvt-ltd> [image:
www_logo] <http://www.altius.cc/>

DISCLAIMER
This e-mail message and information contained herein is proprietary to
Altius Customer Services Pvt Ltd and or its Customers and is intended only
for the personal use of the recipient(s) named above. This message may be
an attorney-client communication and as such privileged and confidential.
If you are not an intended recipient, you may not review, copy or
distribute this message. If you have received this communication in error,
please notify us immediately at ***@***.*** and delete the original
message. This e-mail may contain viruses. Altius has taken every reasonable
precaution to minimize this risk, but is not liable for any damage you may
sustain as a result of any virus in this e-mail. You should carry out your
own virus checks before opening the e-mail or attachment. Altius reserves
the right to monitor and review the content of all messages sent to or from
this e-mail address. Altius is neither liable for the proper and complete
transmission of the information contained in this communication nor for any
delay in its receipt. Messages sent to or from this e-mail address may be
stored on the Altius e-mail system.
