### ISSUE TITLE
Article for upgrading from handsontable is missing

### ISSUE THREAD

**Issue by MarkusWollny** [paulhodel/jexcel#1535]
The readme states "If you have questions, you can review the article upgraging from Jspreadsheet v2 or Handsontable." - this article however is nowhere to be found. Has this been removed for some legal reasons or did I just not look in the right place?

**Comment by GBonnaire** [comment]
Hi,

I can't answer this question. Maybe @hodeware can tell you more ?

Have good day

**Comment by hodeware** [comment]
No longer available.
