### ISSUE TITLE
load async data

### ISSUE THREAD

**Issue by isbincApps** [paulhodel/jexcel#1536]
hi, how i can filter async data without a url
```
o.filter = async (instance, cell, c, r, source) => await self.debounceSearch(instance, cell, c, r, source, v)

```

**Comment by GBonnaire** [comment]
Hi,

Do you want load full data and filter after ?

**Comment by isbincApps** [comment]
hi, i want to filter async, because the data is so large

**Comment by isbincApps** [comment]
hi, how can i do it?

**Comment by hodeware** [comment]
If you are loading too much information you might consider upgrading to a Professional version.
