### ISSUE TITLE
Enter date manually in datepicker component

### ISSUE THREAD

**Issue by paulojribp** [paulhodel/jexcel#1540]
Hi, I'm trying to insert a datepicker component that the user can enter manually the date or select in popup. I'm trying various ways but can't achieve it.
I saw that version 2 has this feature, but it is deprecated: https://bossanova.uk/jspreadsheet/v2/examples/using-a-calendar-column-type

There is any way to do this? Or are you thinking in implement something like this?

**Comment by GBonnaire** [comment]
Hi,

Yes you can't with calendar component.

2 possibilities :
use text mask in option
{ type: 'text', mask:'dd/mm/yyyy' }

Or use custom editor
https://bossanova.uk/jspreadsheet/v4/examples/column-types


You can try to use this : https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/tree/master/editors/dates
But it's for JSS Pro, i don't test if it work en CE version

**Comment by hodeware** [comment]
V2 is depreacted. Please update to a most recent version.
