### ISSUE TITLE
Datepicker format (year) changes - Just started happening

### ISSUE THREAD

**Issue by HOA-MAROON** [paulhodel/jexcel#1542]
just starting having datepicker issues. Everything has ben working fine for 2 years. Problem is the date format seems to change when the date is prepopulated in the spreadsheet column. Initially I use the datepicker to select a date and it is fine. Then I save the spreadsheet to the database. When I retrieve the data the date is populated correctly, but when I click to change it the datepicker popups with the wrong year and day. Date sane is 05/02/2022 and the datepicker reads it as 05/11/05. You can see the year in the datepicker as May 5. Other blank cells in same column show the date correctly when you popup the datpicker. 

See attached for example

Here is the column setup
            { type:'calendar',
                title:'Period\nof\nPerformance\nFrom',
                options: { format:'MM/DD/YYYY', time:0 },
                width:'100'},
            { type:'calendar',
                title:'Period\nof\nPerformance\nTo',
                options: { format:'MM/DD/YYYY', time:0 },
                width:'100'},  

![jsexcel datepicker issue](https://user-images.githubusercontent.com/51753299/167892028-d3485449-aeb8-4393-94a9-0d7abf66f982.PNG)

**Comment by HOA-MAROON** [comment]
I did some more research. I am on version 4.2.3 and jsuite 3. I also am saving the date as a character type and not as a date type.

I looked at the calendar and see that the default date format is YYY-MM-DD. When I put the date formatted that way in the database, the column is populated with the date but in the format in my initialization file (mm/dd/yyyy). Then when I popup the calendar the date it defaults is correct. It looks like the when the default date when the calendar popups ups is ignoring the date format that I set and uses the default set in the code.

I will try and convert the date into the format YYYY-MM-DD as I pull it out of the database to test as a possible workaround for this issue

**Comment by HOA-MAROON** [comment]
I created a function to call when I read out of the database to convert the date format from mm/dd/yyyy to yyyy-mm-dd. It appears to be working  as workaround. I did not touch the calendar javascript.

**Comment by hodeware** [comment]
The raw date was always the same yyyy-mm-dd since the first version of both software. This is the format you should define for the raw data, them you can use the format to display in any format you like.

More information:
https://jsuites.net/v4/javascript-calendar
