### ISSUE TITLE
issue in table header title 

### ISSUE THREAD

**Issue by devyaghi** [paulhodel/jexcel#1544]
when the columns in spreadsheet be large for example 16 columns, I notice that the column title cut although I change the size of column and set the tableOverflow to true, what is the problem?, could you please see attached image? 
<img width="1680" alt="Screen Shot 2022-05-23 at 9 18 53 AM" src="https://user-images.githubusercontent.com/25905619/169755677-20d9ec05-614c-4143-8657-6d22eed39535.png">

**Comment by hodeware** [comment]
Can you clarify your question?
