### ISSUE TITLE
How can I check if a manual filter has been applied to any column of a table?

### ISSUE THREAD

**Issue by zehguilherme** [paulhodel/jexcel#1546]
Manual filter, I'm mean, using de `filter` component.

![image](https://user-images.githubusercontent.com/36301054/170061832-dbec62a7-65ba-468f-90f3-ff659dee2700.png)

**Comment by hodeware** [comment]
You can check if one of the positions in the array have values.

console.log(instance.filters)

![image](https://user-images.githubusercontent.com/75275282/171995331-6b043db8-eff2-4d0d-8280-455fc69da764.png)

![image](https://user-images.githubusercontent.com/75275282/171995334-a24cd21e-4ea5-43a6-814f-07aa14688c0a.png)
