### ISSUE TITLE
Can I define an event that fires when the tab is changed?

### ISSUE THREAD

**Issue by dc7303** [paulhodel/jexcel#1550]
Thank you for the wonderful project! 👍 

I am using multiple tabs. And I want to fire an event when the focused tap changes.
I've been looking for a [guide](https://bossanova.uk/jspreadsheet/v4/examples/tabs), but I can't find an answer, so I'll ask. 🙏

**Comment by hodeware** [comment]
Currently, that is only available on the Pro distribution: onopenworksheet

**Comment by scott-watcha** [comment]
Thank you for your reply!

**Comment by dc7303** [comment]
Thank you for your reply!
