### ISSUE TITLE
Dropdown appearance issue

### ISSUE THREAD

**Issue by sirpapy** [paulhodel/jexcel#1552]
Hello, I have a problem with the styling of Jspreadsheet. I am using react and I followed the react implementation but when I use the dropdown column type I have problems with the background. It's transparent and you can't read anything and the first item of the dropdown is "Done" which is not part of the choice When I defined the column data.

Thanks for your help

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/11463215/181367996-9fd470c3-1757-4641-b616-ad5a8177a7ef.png">

`import jspreadsheet from "jspreadsheet-ce";
import "../../../node_modules/jspreadsheet-ce/dist/jspreadsheet.css";

var data = [
       ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2.000,00', '#777700'],
       ['Civic', 'Honda', '2018-07-11', '', true, '$ 4.000,01', '#007777'],
   ];

   let table = jspreadsheet(document.getElementById('spreadsheet'), {
           data:data,
           columns: [
   { type: 'text', title:'Car', width:120 },
   { type: 'dropdown', title:'Make', width:200, source:[ "Alfa Romeo", "Audi", "Bmw" ] },
   { type: 'calendar', title:'Available', width:200 },
   { type: 'image', title:'Photo', width:120 },
   { type: 'checkbox', title:'Stock', width:80 },
   { type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },
   { type: 'color', width:100, render:'square', }
]
   });`

**Comment by GBonnaire** [comment]
Hi, 

Do you use the last version 4.11.1 ?

**Comment by hodeware** [comment]
Please make sure to update to the most recent version and import the jsuites.css
