### ISSUE TITLE
Onsave Event Not Dispatching (Jspreadsheet V8.7 and V9)

### ISSUE THREAD

**Issue by cwyrwas** [paulhodel/jexcel#1553]
Hi guys! I'm a JSpreadsheet Pro subscriber and I'm attempting to hook into the onsave event. As far as I can tell, it isn't firing for me on both V9 and V8.7.

I'm attempting to send back an ID from my server to the client in order to keep my front and back ends in sync. The idea is to process the server response during this event, but it looks like the event isn't getting dispatched.

I can provide my spreadsheet config if that would be helpful. 

Thanks!

**Comment by GBonnaire** [comment]
Hi 😊 

for pro support, you can open issue on https://github.com/jspreadsheet/pro/issues

For your questions : to dispatch event `onsave`, you need define `persistence` or `server` property with url of your server. If you want manage your system of save without persistence. You need to use onchange/onbeforechange/onafterchanges
