### ISSUE TITLE
Filter + scroll Fix

### ISSUE THREAD

**Issue by ricardoperroni** [paulhodel/jexcel#1554]
Hi guys!

I has a problem with filter grid, when using tableOverflow property, however I need change bellow code and it work for me.
Anybody update the code on github or has another idea?

![fix1](https://user-images.githubusercontent.com/26558844/185662651-c4ea3580-b756-43eb-8006-5e33a7eadc2e.png)
![fix2](https://user-images.githubusercontent.com/26558844/185662690-cc689f31-eb26-4461-9edd-4071df8b15d2.png)
![fix3](https://user-images.githubusercontent.com/26558844/185662718-377e9c8e-a40f-403d-be63-9df9f49e75b3.png)

**Comment by GBonnaire** [comment]
Hi,

Yes you are right, could you create a Pull request with this fix ?

Thanks

**Comment by jhorlima** [comment]
Caracas! Você é um gênio, @ricardoperroni! Agradeço demais pela solução :D

**Comment by ricardoperroni** [comment]
Thx!
