### ISSUE TITLE
Drag corner positioned wrongly

### ISSUE THREAD

**Issue by nousernames2** [paulhodel/jexcel#1556]
I have inherited a project where the drag handle on the spreadsheet is displayed in the wrong position.

There is custom padding added to the spreadsheet td cells though removing this doesn't fix the issue.

The further along in columns and rows that you select, the more skewed the drag handle `jexcel_corner` becomes

I'm using it with React and using these settings.

```
      data: rows,
      columns: head,
      pagination: 1000,
      tableOverflow: 'auto',
      defaultColWidth: defaultColWidth,
      search: true,
      editable: false,
      allowExport: true,
      csvFileName: 'sample',
      contextMenu: () => '',
      rowResize: false,
```
      
Screenshots that demonstrate the issue.. 

![Screenshot from 2022-09-03 13-13-00](https://user-images.githubusercontent.com/37215427/188270040-34a0fed0-c562-4149-a44d-03c89a21dcf3.png)
![Screenshot from 2022-09-03 13-13-12](https://user-images.githubusercontent.com/37215427/188270042-66b218f0-4540-4854-9604-4a13a0d0e24b.png)

**Comment by GBonnaire** [comment]
Hi,

In your CSS do you use `transform: scale` ? or equiv ? 

If it's true, you need reset your "zoom" for Jspreadsheet Element.
