### ISSUE TITLE
If Table Data Have  Formulas , Change getJson Function

### ISSUE THREAD

**Issue by duan0098176153** [paulhodel/jexcel#1559]
obj.getJson = function(highlighted) {
            // Control vars
            var data = [];

            // Column and row length
            var x = obj.options.columns.length
            var y = obj.options.data.length

            // Go through the columns to get the data
            for (var j = 0; j < y; j++) {
                var row = null;
                for (var i = 0; i < x; i++) {
                    if (! highlighted || obj.records[j][i].classList.contains('highlight')) {
                        if (row == null) {
                            row = {};
                        }
                        if (! obj.options.columns[i].name) {
                            obj.options.columns[i].name = i;
                        }
                        let newValue=obj.options.data[j][i];
                        if ((''+newValue).substr(0,1) === '=' && obj.options.parseFormulas === true) {
                            row[obj.options.columns[i].name] =obj.executeFormula(newValue, i, j)
                        }else {
                            row[obj.options.columns[i].name] = obj.options.data[j][i];
                        }

                    }
                }

                if (row != null) {
                    data.push(row);
                }
           }

           return data;
        }

**Comment by hodeware** [comment]
If you are interested to send a PR will be much appreciated.
