### ISSUE TITLE
Dynamic data and total summary 

### ISSUE THREAD

**Issue by ogisetiawan** [paulhodel/jexcel#1560]
<img width="867" alt="sales forecast" src="https://user-images.githubusercontent.com/15768370/192136905-9b728347-614e-494f-87b3-1555cd18433c.png">

Dear @pphod,

May i ask, i already read the documentation and try it, but i have a form like this, can i develop using Jexcel :
1. Dynamic total, meaning, can i split some rows to create a Total, e.x i have data Commision Coating and Commision Construction then can i create a total Comission as dynamic,
2. after i have a total dynamic, can i count to create a all total e.x Total Commision + Total Ex-stock = Total All
3. can i create a dropdown to create an event, for example i have a dropdown have values Yes and No, if I select Yes, it will call the event to change the value in the next celli or if select no, certain cells will be readonly

Thank you!

**Comment by GBonnaire** [comment]
Hi,

look at the documentation for the footer, you can do something close to or/and I think the best solution is to use the 'onevent' or 'onchange' property to detect the change value and then after you will put the new value directly on the footer cell. (On the Pro version it's easier than the CE version: www.jspreadsheet.com )

https://bossanova.uk/jspreadsheet/v4/examples/footers

https://bossanova.uk/jspreadsheet/v4/examples/footers

**Comment by ogisetiawan** [comment]
> Hi,
> 
> look at the documentation for the footer, you can do something close to or/and I think the best solution is to use the 'onevent' or 'onchange' property to detect the change value and then after you will put the new value directly on the footer cell. (On the Pro version it's easier than the CE version: [www.jspreadsheet.com](http://www.jspreadsheet.com) )
> 
> https://bossanova.uk/jspreadsheet/v4/examples/footers
> 
> https://bossanova.uk/jspreadsheet/v4/examples/footers

Thanks for the response, but i already read it in there we don't see to use dynamic data , meaning i need to split some footer. 

![image](https://user-images.githubusercontent.com/15768370/192301155-8fb42c05-6be0-4a6f-af22-9c84aa3721bf.png)

lets say i have data a,b,Total AB, d,e, Total DE and Total ABDE the data has defined because i call from API, so can i split and define the formula for Total AB, Total DE and Total ABDE?

**Comment by hodeware** [comment]
Sorry, I think it is a bit late on this topic. Please feel free to send any additional information.
