### ISSUE TITLE
Mask problems with negative sign

### ISSUE THREAD

**Issue by marcosaso** [paulhodel/jexcel#1561]
Hi guys,

Thanks for this great lib!!!
There is a issue in the formulas when using a negative sign in a currency mask without RED.

Ex.: 
https://bossanova.uk/jspreadsheet/v4/examples/column-types
{ type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },

If you insert a negative value in any cell of "Price column" and try to calculate it in other cell, It will return a NaN value. Like this:

I inserted a new column (G) after the price column and calculeted "price value / 2" :
G1 value = -F1/2
G2 value = -F2/2

<img width="998" alt="Captura de Tela 2022-10-03 às 04 57 38" src="https://user-images.githubusercontent.com/18434900/193527927-2ea1295b-8197-435a-841f-4174867738e1.png">

The issue is in the "parseNumber" function that doesn't accept a negative number as a valid number. The fix is in line that checked if number[0] is a valid number:

![Captura de Tela 2022-10-03 às 04 49 32](https://user-images.githubusercontent.com/18434900/193526482-999ffe3e-47b2-45e0-b649-0656b8ed1c22.png)

If the Jspreadsheet's developers prefer, I can send a pull request.
Regards,

Marcos

**Comment by GBonnaire** [comment]
Hi,

I think you can send a pull request 😊 

Thanks

**Comment by marcosaso** [comment]
Hi @GBonnaire,

I just did it.
Sorry for the long time this took.
Merry Christmas!
