### ISSUE TITLE
JSSpreadesheet After dropdown selection unable to view the selected option

### ISSUE THREAD

**Issue by vinodkk605** [paulhodel/jexcel#1563]
Hi,

In JSSpreadesheet After dropdown selection unable to view the selected option, when we double click on it, it is showing the selected value. Please go through the below mentioned screenshots. Can anyone please help me on this.

![Capture](https://user-images.githubusercontent.com/114978523/193749302-e704258d-94fd-4e00-a3cd-74f996551f58.PNG)

![image](https://user-images.githubusercontent.com/114978523/193749470-d79950c9-ef6e-4c06-83c1-a3ac7a5b4484.png)

**Comment by GBonnaire** [comment]
Hi,

Do you use last version of jsuites.js ?

**Comment by hodeware** [comment]
Please make sure to declare KEY, VALUE correctly. If that is not correctly defined the result would be a blank value in the cells.
