### ISSUE TITLE
Input field for column type 'calendar' gets cleared half way through user's entry

### ISSUE THREAD

**Issue by plobod** [paulhodel/jexcel#1564]
**Problematic behaviour:**
- defined a column of type `calendar` with the following options:
```
options: {
  readonly: false,
  format: "DD.MM.YYYY"
}
```
- when trying to enter a date manually (instead of picking it from the calendar), after the 3rd key press the input field gets cleared
- next, if I repeat the exact same 3 key presses again, the input gets accepted; if I try to enter a different date, the above repeats
- it works ok without the `format` field, but I need the dates in the same locale format as elsewhere in the applications

You can replicate this behaviour in this sandbox: https://codesandbox.io/s/jspreadsheet-forked-t96tdq?file=/src/App.js

**Expected behaviour:**
- I can enter a date in the pre-defined format manually without the input field getting cleared

**Any idea on how to fix that?**

**Comment by GBonnaire** [comment]
Hi,

Try with this format :  format: "dd.mm.yyyy" instand of DD.MM.YYYY

**Comment by plobod** [comment]
Thanks Guillaume, but unfortunatelly the issue still persists... I updated the linked sandbox accordingly.

**Comment by GBonnaire** [comment]
I don't have the problem with this update on your sandbox.

**Comment by plobod** [comment]
It might have been a browser issue, but it occurs both under Chrome and Firefox, so that is rather unlikely. 

Here is a quick screen capture that shows what the problem is: https://user-images.githubusercontent.com/63853577/196669248-a4d23379-e2b9-43c0-b039-9bbf07794daf.mp4

**Comment by GBonnaire** [comment]
Ok, we found why you have a problem with this format.

A fix have pull requested on jSuites : https://github.com/jsuites/jsuites/pull/126

In waiting, you can use this patch after import jSuites on your code :

```javascript
jSuites.calendar.extractDateFromString = function(date, format) {
    var o = jSuites.mask(date, { mask: format }, true);
    
    // Check if in format Excel (Need difference with format date or type detected is numeric)
    if (date > 0 && Number(date) == date && (o.values.join("") !== o.value || o.type == "numeric")) {
        var d = new Date(Math.round((date - 25569)*86400*1000));
        return d.getFullYear() + "-" + jSuites.two(d.getMonth()) + "-" + jSuites.two(d.getDate()) + ' 00:00:00';
    }
    
    if (o.date[0] && o.date[1]) {
        if (! o.date[2]) {
            o.date[2] = 1;
        }

        return o.date[0] + '-' + jSuites.two(o.date[1]) + '-' + jSuites.two(o.date[2]) + ' ' + jSuites.two(o.date[3]) + ':' + jSuites.two(o.date[4])+ ':' + jSuites.two(o.date[5]);
    }
    return '';
}

```

**Comment by plobod** [comment]
It fixed the problem in the Sandbox. Many thanks for your help!
