### ISSUE TITLE
Selecting (clicking) individual cells in quick succession selects multiple cells

### ISSUE THREAD

**Issue by it-admins-3degreesinc** [paulhodel/jexcel#1566]
Clicking on individual cells in quick succession often selects multiple cells (usually 3, but sometimes 2 or 4 cells), usually in a column above or below the cell that was actually clicked. The far left "row number" column also indicates that cells in multiple rows have been selected.

If you edit (start typing new text) when those multiple cells are selected, it appears that the "proper" cell (the last one you clicked) is the one that's edited, which although correct, but it is very confusing when multiple cells are selected.

Sometimes, after those multiple cells have been selected, clicking on a cell to the right or left of the selected cells will move the selection to that other column, but block the same number of vertically selected cells. In these circumstances, it may take several clicks in and out of the cell you actually want to edit, before the multi-cell column goes away and only that one cell is selected.

We were using version 4.3.2, so I upgraded to 4.6.0, however the issue is still there.

**Comment by hodeware** [comment]
It is very hard from your description give some feedback and I don't think think is a version problem. What would create this is the mouse over cells with mouse clicked. We can screenshare and take a look on the problems you are facing. I am going to close this one, but please send us a message to support@jspreadsheet.com
