### ISSUE TITLE
html code for button is displayed inside cell instead of button being showed

### ISSUE THREAD

**Issue by nchilveru** [paulhodel/jexcel#1567]
below code give output as in image below it. I want a button to be displayed inside a cell. 

   var selectionActive = function(instance, x1, y1, x2, y2, origin) {
        cellName1 = jexcel.getColumnNameFromId([x1, y1]);
        colno1 = y1+2;
    } 

  var insertNewRow = function(instance, rowNumber, numOfRows, rowRecords, insertBefore){
      nxt_cell_id="Q"+colno1;
      myTable.setValue(nxt_cell_id,addSaveRowBtn(nxt_cell_id));
    }

    var myTable=jspreadsheet(document.getElementById('table'), {
        data: op_data,
        columns: [
            { type: 'text', width:40 },
            { type: 'text', width:50 },
            { type: 'text', width:50 },
            { type: 'text', width:70 },
            { type: 'text', width:55 },
            { type: 'text', width:55 },
            { type: 'text', width:65 },
            { type: 'text', width:65 },
            { type: 'text', width:50 },
            { type: 'text', width:100 },
            { type: 'text', width:100 },
            { type: 'text', width:100 },
            { type: 'text', width:100 },
            { type: 'text', width:80 },
            { type: 'text', width:80 },
            { type: 'text', width:80 },
            { type: 'text', width:40 }
            
        ],
        onselection: selectionActive,
        oninsertrow: insertNewRow,
    });

    function addSaveRowBtn(cellno){
        html_cont='<button type="button" id="'+cellno+'_save" class="btn btn-secondary" onClick=saveRow();>Save</button>';
        return html_cont;
    }

**output** 
![image](https://user-images.githubusercontent.com/22763737/196134910-6a028384-19bc-477f-8caa-a4a2e2eee270.png)

**Comment by ricardoperroni** [comment]
Hi nchilveru,

You tried change columns type  to htmls type?

![image](https://user-images.githubusercontent.com/26558844/196172689-036ee4ee-792f-4d76-8098-7712186b6887.png)

**Comment by nchilveru** [comment]
Thanks. That solved the issue.
