### ISSUE TITLE
Export to excel using version 3.9

### ISSUE THREAD

**Issue by StacyMullins** [paulhodel/jexcel#1568]
Currently using an outdated version: 3.9 and can not find any comprehensive documentation for exporting to xlsx
Please advise.

**Comment by GBonnaire** [comment]
Hi

Try this code : 

```
myTable.download();
```

This method generate a CSV file

**Comment by hodeware** [comment]
You have support for XLSX in the PRO distribution as below. There is no support for XLSX export on CE.
https://jspreadsheet.com/products/export-to-xlsx
