### ISSUE TITLE
Dropdown closed from column position 14

### ISSUE THREAD

**Issue by jlgarcia-vs** [paulhodel/jexcel#1569]
Hello,

Thank you very much for this awesome library!
I've found a strange problem with a column of type dropdown.

The column with the dropdown is in position 14 and the dropdown is not displayed when double click. I've tried to put some break points in index.js (jspreadsheet) code and I can see opening the dropdown but when the index.js file calls jSuites script [ jSuites.dropdown(editor, options); ] the dropdown disappear.

If I move the column to a previous position (for example any column from 1 to 13) the dropdown works as expected, but any column from 14 does not open the dropdown.

Data for dropdown column is loaded from json file with around 800 rows.

Any idea about what could be causing this problem?
Regards

**Comment by GBonnaire** [comment]
Hi,

Can you reproduct this problem on JSFiddle?

**Comment by jlgarcia-vs** [comment]
HI @GBonnaire,

Yes, I've created a fiddle and it's failing also.
I think the problem happens when the excel has a predefined width and the column with the dropdown is outside the viewing range.

If you move the column to a prior position, it's working fine. I think the problem only happens when it's the last column and outside of visible area.

[Example](https://jsfiddle.net/crkjl/uLfjh0pk/3/)

**Comment by GBonnaire** [comment]
Hi,

In your case, to fixe the problem you can add in your onload JSS : 

```javascript
jspreadsheet(El, {
/* your config */
onload: function(el, obj) {
        obj.table.style.marginRight = "5px";
    },
});
```

**Comment by jlgarcia-vs** [comment]
Hi @GBonnaire

Thats fixed the problem.
Thanks a lot for your help.

Regards
