### ISSUE TITLE
Unable to Copy from cells but able to paste into them

### ISSUE THREAD

**Issue by nchilveru** [paulhodel/jexcel#1570]
I am unable to copy from cells of jspreadsheet table either by CTRL + C or right click copy command but I am able to paste into the those cells. I am using chrome browser. Kindly guide.

**Comment by GBonnaire** [comment]
Do you use this framework on localhost, or http wihout ssl ?

**Comment by nchilveru** [comment]
currently i am using on localhost, but i will eventually move it to http probably without ssl.

**Comment by GBonnaire** [comment]
Eventually, if you can't copy, maybe search in your libraries and code, if you don't have window.addEventListener with key listiner or copy listener 

The copy command is browser dependent (API command copy). And try with an other browser if you have same problem.

Warning : In localhost, in HTTP and in HTTPS, you will have different behavior of copy result
