### ISSUE TITLE
Implement "sum_range" in SUMIF formula ?

### ISSUE THREAD

**Issue by ouatataz** [paulhodel/jexcel#1572]
The syntax for the SUMIF function should be : `SUMIF(range, criteria, [sum_range])`

The SUMIF function syntax should have the following arguments:

- `range`   Required. The range of cells that you want evaluated by criteria. Cells in each range must be numbers or names, arrays, or references that contain numbers. Blank and text values are ignored. The selected range may contain dates in standard Excel format.

- `criteria`   Required. The criteria in the form of a number, expression, a cell reference, text, or a function that defines which cells will be added. Wildcard characters can be included - a question mark (?) to match any single character, an asterisk (*) to match any sequence of characters. If you want to find an actual question mark or asterisk, type a tilde (~) preceding the character.

- `sum_range`   Optional. The actual cells to add, if you want to add cells other than those specified in the range argument. If the sum_range argument is omitted, Excel adds the cells that are specified in the range argument (the same cells to which the criteria is applied). Sum_range should be the same size and shape as range. If it isn't, performance may suffer, and the formula will sum a range of cells that starts with the first cell in sum_range but has the same dimensions as range.

Would it be possible to include the `sum_range` argument ?
Many thanks in advance !

**Comment by hodeware** [comment]
JSS uses formulajs, so I belive that has improvements.
