### ISSUE TITLE
Table overflow + "contextMenuControls" bug

### ISSUE THREAD

**Issue by ouatataz** [paulhodel/jexcel#1573]
To reproduce this bug : 

- Go to : https://bossanova.uk/jspreadsheet/v4/examples/table-overflow
- Right-click on a column header : the context menu appears, select "delete selected columns"
- Right-click on another column header : the context menu won't show

Errors in console : 
```
Uncaught TypeError: jexcel.current.selectedCell is null
contextMenuControls index.js:14135
build index.js:13250
init index.js:12825
jexcel index.js:13183
<anonymous> table-overflow:262
EventListener.handleEvent* table-overflow:261
```

**Comment by Ruan-Miguel** [comment]
This error was fixed on v5
