### ISSUE TITLE
Add the `jexcel` property to the `instance` in `DefinitelyTyped`.

### ISSUE THREAD

**Issue by k4a-l** [paulhodel/jexcel#1576]
To get the jexcel methods etc. in the jspreadsheet event, write as follows
```ts
  (instance: any, cell, c, r, source) => {
    const value = instance.jexcel.getValueFromCoords(...) ;
```

Currently [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jspreadsheet-ce/index.d.ts#L400)'s ` instance` is typedefed as `HTMLElement`, is it possible to add a `jexcel` property as follows?

```ts
instance: HTMLElement & { jexcel: JSpreadsheetElement }
```

I can define the above myself in a TypeScript project, but it would be very helpful if it existed at the time of DefinitelyTyped.

**Comment by hodeware** [comment]
We are reviewing the @types, and we should include that on the next release. @Ruan-Miguel
