### ISSUE TITLE
Multi-cell selection bug?

### ISSUE THREAD

**Issue by it-admins-3degreesinc** [paulhodel/jexcel#1578]
Hi,

We're trying to determine if a particular behavior in jexcel is somehow unique to our setup, or if it's a known bug.

When moving quickly between different cells - clicking, not arrowing - instead of selecting just the last cell you clicked, it sometimes arbitrarily selects 3 or 4 cells in a vertical column where the cell you last clicked is usually either at the top or bottom of that column of selected cells.

Is this a known issue? And if it is, is there a fix or workaround?

We experienced this in version 4.3.2, and still after we upgraded to version 4.6.0.

Thanks for your help.

**Comment by hodeware** [comment]
It is probably because JSS is trying to bring the cell to the viewport and moving your new cell to the cursor, and since your click is down, it is creating this behavior.

**Comment by it-admins-3degreesinc** [comment]
Hi hodeware,

Thank you for getting back to me. 

Is this a bug? or is it something we can somehow avoid? I suspect that "clicking more slowly" might help, but it's tough to tell the users to slow down when that could negatively impact their productivity.

Any suggestions on how we can remedy this would be much appreciated.

Thank you!

**Comment by hodeware** [comment]
Not exact a bug, but more a limitation of the viewport and events in place. Did you have a chance to try version 9 the viewport is much better and you can handle much more data without hiccups. Please send us a message on support@jspreadsheet.com and we can try to help you improve your solution.
