### ISSUE TITLE
CSRF Token in POST request

### ISSUE THREAD

**Issue by IksanovRoman** [paulhodel/jexcel#1579]
I use jspreadsheet v4. I write in Django using DRF. I GET my data from JSON, then use data persistense to update my data in the table and then POST request to save my data in JSON format in my database. But i get error 403 forbiden. I read this might be because i don't send CSRF Token with my POST request, but Django requires this token. How can i send this token with my data?

**Comment by hodeware** [comment]
You can try to define a global beforeSend event for jSuites.ajax.beforeSend = function(xh) { // add headers to the call  }
