### ISSUE TITLE
Multiple types exist in one column

### ISSUE THREAD

**Issue by nobugr** [paulhodel/jexcel#1580]
How can I achieve that there are only multiple types in one column, such as checkbox and dropdown coexisting in one column, like real excel

**Comment by hodeware** [comment]
That is a feature available only in the Pro version. See this example:
https://jspreadsheet.com/v9/cases/payment-calculator

**Comment by nobugr** [comment]
> That is a feature available only in the Pro version. See this example: https://jspreadsheet.com/v9/cases/payment-calculator

thanks
