### ISSUE TITLE
Consider using textContent rather than innerText

### ISSUE THREAD

**Issue by davidroeca** [paulhodel/jexcel#1582]
Is there a rationale for setting `innerText` rather than `textContent` in the `setData` function? 

They do behave a bit differently -- I think textContent allows for more whitespace in some scenarios. However, [it also appears to be faster](https://kellegous.com/j/2013/02/27/innertext-vs-textcontent/) than `innerText` which may be a nice added bonus to an already fast spreadsheet library.

Context: I had to dig pretty deep to understand why my tests were failing -- they rely on [jsdom](https://github.com/jsdom/jsdom) which is the go-to headless engine for [jest](https://jestjs.io/). Turns out that [jsdom doesn't support innerText](https://github.com/jsdom/jsdom/issues/1245) due to its reliance on a layout engine. So for me, mocking `innerText`'s setter and getter to be `textContent` helped make my tests pass. The workaround mentioned in the jsdom issue solved my problems, so I'd call this a suggestion rather than a request. But it could help users who write react applications and end up using a testing suite such as Jest that relies on jsdom.

**Comment by hodeware** [comment]
That is a good suggestion and we will implement that as as soon as possible.

**Comment by hodeware** [comment]
v4.11.0+ implement those changes. We are adopting some tests using jsdom. If you have something to share it would be much appreciated.

**Comment by davidroeca** [comment]
@hodeware here's what I used for `innerText`. There are still issues interacting with the table, but this works for reading what's in the table

```js
// Taken from below (with a setter as well):
// https://github.com/jsdom/jsdom/issues/1245#issuecomment-445848341
// This is required for jspreadsheet tests to work appropriately, since
// jspreadsheet's createCell function updates innerText
Object.defineProperty(global.Element.prototype, 'innerText', {
  get() {
    return this.textContent
  },
  set(value) {
    this.textContent = value
  },
  configurable: true,
})
