### ISSUE TITLE
Event keyDownControls remains active even if element no longer exists

### ISSUE THREAD

**Issue by nightrider77** [paulhodel/jexcel#1584]
The problem is that

`document.addEventListener("keydown", jexcel.keyDownControls);`

Remains active even when jspreadsheet object no longer exists.

And if you initialize jspreadsheet again on the same page, this keyDownControls event will fire twice, thrice, ... (depends on how many times you have initialized jspreadsheet).

This isn't good.

I think there should be added some instance ID to jspreadsheet html element, and if there is no html element on page, event must be unregistered.

And imagine you have 2 jspreadsheet objects. You press Del, and it fires on both jspreadsheet objects, as keyDownControls doesn't know on which jspreadsheet object it was triggered...

**Comment by nightrider77** [comment]
For example, you can use https://github.com/jherax/handle-events

**Comment by hodeware** [comment]
// You have a option to destroy the element, removing all event handlers. It is a boolean argument on the destroy function.
jexcel.destroy = function(element, destroyEventHandlers);

**Comment by hodeware** [comment]
We have added a condition to protect against duplicate events.
