### ISSUE TITLE
Using TAB to close HTML editor doesn't work

### ISSUE THREAD

**Issue by marcosaso** [paulhodel/jexcel#1589]
Hi guys,
Thanks for giving us this great lib!!!

The pattern of closing the editor when pressing TAB does not work in the HTML editor, which brings unpredictable errors, such as when pressing TAB in the example of the site:
https://bossanova.uk/jspreadsheet/v4/examples/richtext-html-editor

The editor remains open as shown in the print of the page even after leaving the worksheet and going to the end of the page:

![Captura de Tela 2022-12-25 às 02 58 42](https://user-images.githubusercontent.com/18434900/209458575-9eb4ab7a-5170-4e91-8217-7f7b283295cf.png)

Does anyone know how to fix this?
Thanks a lot!

Marcos

**Comment by GBonnaire** [comment]
Hi,

In waiting fix on jspreadsheet, you can set this on event oneditionstart

```javascript
oneditionstart: function() {
    document.querySelector(".jexcel_richtext").editor.options.onblur = function() { 
       jspreadsheet.current.closeEditor(jspreadsheet.current.getCellFromCoords(...jspreadsheet.current.selectedCell), true);
   }
}
```

Is not a good solution, but you can close on tab editor

**Comment by marcosaso** [comment]
Hi @GBonnaire,

Thanks for reply.
I've tried that fix, but 
document.querySelector(".jexcel_richtext")
is returnning "null".

I've tried others ways to get ".jexcel_richtext" like using getElementsByClassName's method but in all this cases, it return null.

Do you have any idea what is wrong?

**Comment by GBonnaire** [comment]
this editor is accessible only if cell is on edit mode

**Comment by marcosaso** [comment]
Hi @GBonnaire,

I looked it up here and indeed the oneditionstart event is called before the creation of the jexcel_richtext component.

https://github.com/jspreadsheet/ce/blob/fbcc95aaf18e96b831e0770717b05210be4a297c/dist/index.js#L7836

https://github.com/jspreadsheet/ce/blob/fbcc95aaf18e96b831e0770717b05210be4a297c/dist/index.js#L7842

https://github.com/jspreadsheet/ce/blob/fbcc95aaf18e96b831e0770717b05210be4a297c/dist/index.js#L7961

So inside the oneditionstart event,
  document.querySelector(".jexcel_richtext") will always return null.

So I would have to fix this issue in another event after creating the jexcel_richtext component (line 7961).
Would there be any other event that could fit this?
Thanks

**Comment by GBonnaire** [comment]
Absolutely.

try this on your configuration instead of previous event configuration

```javascript
oncreateeditor: function(el, cell, x, y, editor) {
        setTimeout(function() {
            editor.querySelector(".jexcel_richtext").editor.options.onblur = function() { 
                jspreadsheet.current.closeEditor(jspreadsheet.current.getCellFromCoords(...jspreadsheet.current.selectedCell), true);
            }
        }, 1);
    }
```

**Comment by marcosaso** [comment]
Hi @GBonnaire,

Thanks for your reply.

This actually works in the oncreateeditor event.
Unfortunately it generates a side effect tough:

The ESC key also generates the unblur and thus it loses the effect of canceling the change in the HTML editor. :(

Anyway, I found how to solve this in jspreadsheet ce code.
I'm going to send a pull request.

**Comment by marcosaso** [comment]
@GBonnaire 

Like you describe with your code, "jspreadsheet.current.closeEditor" have to trigged when TAB key is pressed for HTML editors.

So, it is the same behavior implemented for calendars components.

I found it in to the code of calendar component and fix it in my commit: https://github.com/jspreadsheet/ce/commit/9fa636d054bcd0068d219509a149bdb5aee6ba48

**Comment by hodeware** [comment]
Version 9 includes this feature.
