### ISSUE TITLE
jspreadsheet not working on server 

### ISSUE THREAD

**Issue by Ramlanka7** [paulhodel/jexcel#1593]
I am using trail version of https://jspreadsheet.com/v9/

When I am testing locally, it is working fine. 

When I deploy it, Grid shows up but I am unable to edit any cell, dropdowns not working.

I don't see any errors in Console either.

What could be the issue?

**Comment by hodeware** [comment]
Go to your profile > authorized domains > add your domain > save the profile > get the new license and update your env.
