### ISSUE TITLE
Bug in exports.LEN

### ISSUE THREAD

**Issue by gtasker10** [paulhodel/jexcel#1594]
The code in 4.10.3 has:

            if (typeof text === 'string') {
                return text ? text.length : 0;
            }

            if (text.length) {
                return text.length;
            }

            if (text == null) {
                return 0;
            }

The check for NULL needs to happen before using "text" (two IF blocks earlier)

**Comment by hodeware** [comment]
@Ruan-Miguel

**Comment by hodeware** [comment]
JSS CE uses formulajs now, so any changes to the formulas should be on formulajs repository.
