### ISSUE TITLE
First keyboard typing in international languages

### ISSUE THREAD

**Issue by rsauto9311** [paulhodel/jexcel#1599]
My English keyboard typing is good.
Hangul is entered in English in the first keyboard typing.

The PRO version is entered normally.
For the CE version, the first type is entered in English.

https://user-images.githubusercontent.com/54504666/222483904-41b104c3-2f91-4aab-b932-f116d9d6596c.mp4

**Comment by hodeware** [comment]
Yes, that is a known limitation of CE. This is not possible to fix on CE since uses an editor to each cell. On PRO that was fix from version 8 and improve on version 9 when the editor is a centralized element.
