### ISSUE TITLE
References to "jspreadsheet" instead of "jexcel" in the code

### ISSUE THREAD

**Issue by gtasker10** [paulhodel/jexcel#1603]
A recent commit put references to "jspreadsheet" instead of "jexcel" in the code that checks if the spacebar was pressed to start edition

// Characters able to start a edition
if (e.keyCode == 32) {
    // Space
    e.preventDefault()
    if (**jspreadsheet**.current.options.columns[columnId].type == 'checkbox' ||
        **jspreadsheet**.current.options.columns[columnId].type == 'radio') {
        **jspreadsheet**.current.setCheckRadioValue();
    } else {
        // Start edition
        **jspreadsheet**.current.openEditor(**jspreadsheet**.current.records[rowId][columnId], true);
    }
} else if (e.keyCode == 113) {

**Comment by stephanestermann** [comment]
Jexcel has been renamed to Jspreadsheet.
https://github.com/jspreadsheet/ce/releases/tag/v4.6.0

**Comment by gtasker10** [comment]
@stephanestermann The code had mistakenly replaced "jexcel" with "jspreadsheet" on 5 lines causing an exception to be thrown any time focus was on a radio or checkbox element and the user pressed the spacebar.  The code all still references "jexcel".  Only the name of the library changed
