### ISSUE TITLE
jcontextmenu styles missing from jspreadsheet.css

### ISSUE THREAD

**Issue by tograh** [paulhodel/jexcel#1606]
If I import only jspreadsheet.css, context menus show up in the flow underneath the table.  To get the proper styling, I had to extract the .jcontextmenu content from https://jsuites.net/v4/jsuites.css and include it manually.

Shouldn't the .jcontextmenu styles be included in jspreadsheet.css?

**Comment by hodeware** [comment]
Actually the contextmenu is a jsuites component. Jsuites is a dependency that you need to import to run JSS properly. So, you need to include the whole jsuites.css on your project to get correctly running.

**Comment by tograh** [comment]
If that was mentioned in the project markdown, I missed it.  Using npm to import the project as-is does not result in properly functioning context menus.
