### ISSUE TITLE
Get total page number and programmatically change to the last page. 

### ISSUE THREAD

**Issue by syafiq-dev** [paulhodel/jexcel#1609]
Hi,

Is there any way to change to the last page of a table by code. Such as.

```
var totalPage = myTable.getTotalPage()

// go to last page
myTable.page(totalPage)
```

 I'm using the CE version by the way. Thank you!

**Comment by hodeware** [comment]
You need to calculate, so it would be something like that.
myTable.page(Matil.ceil(myTable.rows.length/myTable.options.pagination));
