### ISSUE TITLE
Merged rows (cells) doesn't work with pagination

### ISSUE THREAD

**Issue by marcosaso** [paulhodel/jexcel#1610]
Hi guys,
Thanks for this great lib!!!

There is a issue when you merge more rows then it can fit on one paginations total lines.

For example: If there is a merged cell with 11 rows merged, when use pagination = 10, it will broke the 11 line (on the second page). Like this:

11 Merged rows ok in pagination with 25 lines:

![Captura de Tela 2023-04-16 às 07 26 51](https://user-images.githubusercontent.com/18434900/232299851-832ad823-60df-4dcd-b24e-1ece5d1c5ca9.png)

However, when it changing the pagination to 10 lines, line 11 will break:

1st page with 10 lines: 

![Captura de Tela 2023-04-16 às 07 40 54](https://user-images.githubusercontent.com/18434900/232300301-59822c33-1ef4-4293-a649-0c47f72ec3f4.png)

And the second page has a broken line (line 11).
The referring values of the sixth, seventh and eighth columns ("Destino", "UN" and "Valor") were incorrectly moved to the first columns (first to third columns) and the remaining cells are broken (they do not show neither the values nor the borders).

![Captura de Tela 2023-04-16 às 07 43 33](https://user-images.githubusercontent.com/18434900/232305411-44243ce2-2d3b-42c3-acd0-8084b6e4028c.png)

The solution would be to not break the merged lines. The merged rows stay on the first page (in this example).

Does anyone know how to fix this?
Or where in the code can I try to fix it?
Thanks a lot!

Marcos

**Comment by hodeware** [comment]
This is a known limitation up to version 8 (CE & PRO), a solution comes on version 9 (PRO-only) when was implement a smarty dom managment and viewport. So, unfortunatelly there is no solution for that on the CE distribution.
