### ISSUE TITLE
How to add a text color button inside the html type column

### ISSUE THREAD

**Issue by shivank-singh75** [paulhodel/jexcel#1615]

**Comment by shivank-singh75** [comment]
![image](https://github.com/jspreadsheet/ce/assets/46323224/5059f2e2-72dd-499c-b874-b7e79ed6bcdd)

**Comment by hodeware** [comment]
You can customize the toolbar. More about the options available
https://jsuites.net/v4/javascript-html-editor/custom-toolbar
