### ISSUE TITLE
When will jspreadsheet/ce release a new version?

### ISSUE THREAD

**Issue by akarnok** [paulhodel/jexcel#1616]
The latest version of jspreadsheet/ce 4.6.0 has been released for more than two years. Can you release a new version?

**Comment by hodeware** [comment]
The works for a version 5 has already started, but we don't have a estimated to give. We have been releasing patchs for v4 for example the types we have included a few months ago and we have finalize release Jsuites 5 a few months ago. We are working on the documentation for that but it is already on the NPM, brings types, etc.
