### ISSUE TITLE
JExcel Status and JExcel Formula Evaluation Bug

### ISSUE THREAD

**Issue by juan-fuentes-sis** [paulhodel/jexcel#1628]
Dear Paul,

Posting here since I didn't get feedback from email.

I hope you are doing well, I can see you have done quite a bit of work in JExcel since the last time we exchange an email.

From our side we continue supporting JExcel in our product even if we have not move yet to the latest version. But this will happen during this year when we do our forms rewrite. I hope you continue supporting the same APIs!!

One of our users reported a bug evaluating formulas that I could reproduce in your web example, I think this is worth looking into because it affects a core feature, formulas evaluation. I hope the screenshot is self explanatory but let me know if clarifications are needed.

Under any case let me know if continue taking sponsorships, I would expect we may need some work during the year.

Have a good day,
Juan

[cascading-simple-formula-original.xlsx](https://github.com/jspreadsheet/ce/files/11866158/cascading-simple-formula-original.xlsx)
![cascading-simple-formula-web-jspreadsheet-error](https://github.com/jspreadsheet/ce/assets/123765486/e6e10d4e-b38f-462e-a4f6-f518fc397683)
[cascading-simple-formula-web-jspreadsheet-save.csv](https://github.com/jspreadsheet/ce/files/11866159/cascading-simple-formula-web-jspreadsheet-save.csv)

**Comment by hodeware** [comment]
There were some updates yestarday that should be improve this. Please upgrade your JSS version.

**Comment by juan-fuentes-sis** [comment]
We will test and let you know. Thanks!

**Comment by juan-fuentes-sis** [comment]
Did you test the example provided? The problem still persists for me, I still got a NaN. 

When calculating the formula: 
=(G4+G5+G6+G7)/(G2+G3+G4+G5+G6+G7+G9)

It seems like the problem lies on the second part, if I substitute it, calculating that part in another cell it works.
=(G4+G5+G6+G7)/H14

But of course this will mean than in complex spreadsheets is required to have lots of additional artificial cells that is a big NONO.

Hope this helps to find what is wrong.

**Comment by hodeware** [comment]
Here is a working example:
https://jsfiddle.net/wqo3r1hx/3/

**Comment by juan-fuentes-sis** [comment]
I'm very sorry to have reopened the issue twice, I didn't realise I was testing the wrong version.

Thanks for taking care of this.
