### ISSUE TITLE
Issue of the first character being inputted in English during IME mode

### ISSUE THREAD

**Issue by sunaga104** [paulhodel/jexcel#1630]
I am truly appreciative of this project, but I've encountered an issue when inputting in Japanese using IME mode; the first character is being entered in English. Upon inspecting the code, it seems that an input tag is being generated simultaneously with the keydown event, which appears to be preventing the first character from being inputted in IME mode. Notably, this issue does not occur with the Pro version.

Is there any intention to address this issue in the future for the CE version? I kindly request a fix for this bug if possible.

This issue is related to the following previous issues:
https://github.com/jspreadsheet/ce/issues/1417
https://github.com/jspreadsheet/ce/issues/883

**Comment by hodeware** [comment]
That is not a bug, it is more a limitation on the structure how the editors works on the CE distribution. There are not plans to include that on the CE, and this feature is already available on the Pro distributions.

**Comment by sunaga104** [comment]
Thank you for your response. I understand.
