### ISSUE TITLE
Docs: `defaultRowHeight` is missing

### ISSUE THREAD

**Issue by cyfung1031** [paulhodel/jexcel#1644]
I don't know where is the md file for the docs. I can just open an issue here.

https://bossanova.uk/jspreadsheet/v4/docs/quick-reference

<img width="877" alt="Screen Shot 2023-09-14 at 20 56 26" src="https://github.com/jspreadsheet/ce/assets/44498510/a04a0a06-9ee6-4aca-a969-9a18e8f979fa">

**Comment by hodeware** [comment]
This property is only available on the PRO version.
