### ISSUE TITLE
update source in a specific cell

### ISSUE THREAD

**Issue by victorLessa** [paulhodel/jexcel#1645]
How to update the options in a drop-down list in a specific cell?
Possui algo como:
```

const cell = sheet.getCell(row, column);
const option = { value: "Opção 4", label: "Opção 4" };

cell.setOptions([...cell.getOptions(), option]);
```

**Comment by Karolis-Stoncius** [comment]
Hi, did you find a solution?

**Comment by hodeware** [comment]
That is only available on the PRO version.
https://www.jspreadsheet.com/docs/cells
