### ISSUE TITLE
Formula automatic updates range but not the result value

### ISSUE THREAD

**Issue by ps91** [paulhodel/jexcel#1649]
Hi,

I'm testing a simple formula `SUM(B1:B4)` where the column `B` is of type number and the formula is in the last line in another column. I want to be able to add a new line in the spreadsheet and see the formula update it's value but that's not happening.  The formula updates the range when I add a new line like `SUM(B1:B5)` but never takes into account the value I put in column `B` for that new line. If I change the other lines that already exist it updates but the new line it doesn't do anything. If updates the range of the formula when I add a new column why doesn't it update the value accordingly with the value of the new line?

**Comment by paulorodalves** [comment]
Hi, 

Thanks for your comment. This feature is only available on the Pro version: https://jspreadsheet.com/docs/
You can test in development for free.

**Comment by paulorodalves** [comment]
Hi,

This feature is only available on the Pro version: https://jspreadsheet.com/docs/
