### ISSUE TITLE
Mask price with all symbol

### ISSUE THREAD

**Issue by shadMod** [paulhodel/jexcel#1652]
Among the various masks we can choose is `mask: "#.##,00"`, to this we can add the dollar symbol to set a "price column" (`mask: "$ #.##,00"`).

The problem is that in case we want to put another different symbol (euro or pound or another) the cell crashes

**Comment by hodeware** [comment]
mask: '£ #.##0,00'

**Comment by shadMod** [comment]
![homer-simpson-homer](https://github.com/jspreadsheet/ce/assets/34680122/e9bd069c-ccd1-42f3-910b-fab406dfd162)
