### ISSUE TITLE
Docs: Description of event arguments missing

### ISSUE THREAD

**Issue by soegaard** [paulhodel/jexcel#1656]
The list of events

https://bossanova.uk/jspreadsheet/v4/docs/events

contains event names and short descriptions.

A description of the arguments of these events are missing.

At first, I thought I could see the arguments in the example,
but consider this (from the example):

```
var deletedRow = function(instance) {
    $('#log').append('Row deleted');
}
```

That the second and third arguments are the first row number and the number of rows to be deleted 
is not seen here.

**Comment by hodeware** [comment]
We are working to create a whole new documentation.
