### ISSUE TITLE
Intermittent error in cross-sheet calculations

### ISSUE THREAD

**Issue by JohnPatrickOshaughnessy** [paulhodel/jexcel#1665]
So I have four sheets in memory, all data loaded from the server with jspreadsheet.calculations(false); once all loaded I run jspreadsheet.calculations(true);.

This works for most formulas nearly all the time however I have '#ERROR' appearing in a cell with a cross sheet calculation formula about 75% of the time, the remaining 25% it works fine. With  debugFormulas:true I see the following in my JS console when the error occurs:

![image](https://github.com/jspreadsheet/ce/assets/146020058/69e71dd5-8121-4d07-b807-8fae98f8a743)

Other cross sheet calculations work reliably, including those that target the result of a complex formula.

It seems to be complaining about a ':' character, I can see that the target cell in the target sheet is having its value reported as "SUM(B4:B9)" - Now this is obviously an invalid formula as it's missing the '='. However if I look at the value of the cell directly I see:

![image](https://github.com/jspreadsheet/ce/assets/146020058/382bf017-841b-4aad-bf2c-d8b4fc8f0a8b)

This would indicate that the formula in the target cell is OK, confirmed by the fact that the value displayed in B10 is indeed the expected SUM result. I'm only guessing this is the cause of the error but having spent a couple of days debugging I am running out of ideas. My feeling is that the error only happens when the target cell contains a range within a formula (like "=SUM(A1:A10)") but what's strange is that sometimes it works ok.

**Comment by JohnPatrickOshaughnessy** [comment]
Here's the full stack trace in case it helps:

![image](https://github.com/jspreadsheet/ce/assets/146020058/04ee8c07-57fa-4e55-8d4c-35a6a5dfdb07)

**Comment by JohnPatrickOshaughnessy** [comment]
Sorry posted this in the wrong place. Have reposted in https://github.com/jspreadsheet/pro/issues/304

**Comment by hodeware** [comment]
Hi John,
Which version are you using? Can you contact support@jspreadsheet.com please? We would be happy to assist you.

**Comment by JohnPatrickOshaughnessy** [comment]
It's V10, will send an email
