### ISSUE TITLE
About onafterchanges label:question 

### ISSUE THREAD

**Issue by dgiglio** [paulhodel/jexcel#1668]
Hi to all,

the doc says `onafterchanges` is triggered "after all changes are applied in the table". But what delimits **all** changes?
In other words, I cannot understand the difference between `onchanges` and `onafterchanges`
Thanks in advance.

**Comment by paulorodalves** [comment]
First the onchange will be called for each cell value changed. In the end, onafterchanges will be called once with an array of information about all cell changed.
