### ISSUE TITLE
Data Copying Issue from Excel to Jexcel: Field Addition Problem

### ISSUE THREAD

**Issue by Alhamou** [paulhodel/jexcel#1672]
When I try to copy data from an Excel file to the table inside Jexcel, a problem occurs:
- I select three cells from the Excel table.
- Then I go to the table in Jexcel and select the fields from the bottom up (not from the top down).
- When doing this, new fields are added instead of copying the data as expected.
Please try this on your end. It is a significant problem for those who are copying their files from inside Excel to Jexcel.

https://jsfiddle.net/spreadsheet/5n21ep6s/

**Comment by hodeware** [comment]
This is version 1. There are many improvements available since them, you can try CE (version 4) or PRO (version 10).
