### ISSUE TITLE
Set Page Total dynamically

### ISSUE THREAD

**Issue by jmcintyr150** [paulhodel/jexcel#1673]
I need paging without loading all the data (1 Mil plus records). I want to set the number of pages manually, then when the user clicks next page, I can use the onchangepage event to get the next batch of records.

**Comment by hodeware** [comment]
The logic behind this is set spreadsheet with minDimensions to define the total of rows, them use onchange to trigger the updates of the rows in page. The only problem CE cannot support 1M rows. In that case PRO v11 can handle that. 

See this example with 1 Billion cells
https://jspreadsheet.com/demo
