### ISSUE TITLE
It is possible to remove all columns [BUG]

### ISSUE THREAD

**Issue by anya92** [paulhodel/jexcel#1674]
It is possible to remove all columns (including the first one), if there is more than one, and you select all of them and click "Remove selected columns" from the context menu (e.g. here: [Docs](https://bossanova.uk/jspreadsheet/v4/examples/programmatically-updates)).

But if there is only one column and you try to delete it, it is blocked and you get an error in the console: `Jspreadsheet: It is not possible to delete the last column`.

Would it be possible to introduce a new option to specify whether all columns should be allowed to be deleted? As with rows this was solved with `allowDeletingAllRows`.

**Comment by hodeware** [comment]
If you need to delete all rows and columns you need to destroy it. Them you can create again afterwards.

**Comment by anya92** [comment]
@hodeware Thank you for the response, but it seems there is some misunderstanding. My intention was not to destroy and recreate the table but to point out an inconsistency in behavior when deleting columns. Let me clarify with examples:

1. If there are **multiple columns**, and you select them all to delete, it works, leaving the table with no columns.
![image](https://github.com/user-attachments/assets/f1ff8048-3302-47df-98ba-7f5db12b8135)
![image](https://github.com/user-attachments/assets/0e2cb85a-1f05-485f-8ced-886d5a7c98d7)

2. However, if there is only **one column** and you attempt to delete it, the operation is blocked, and an error appears in the console:
![image](https://github.com/user-attachments/assets/d2c85a66-e091-4993-90d1-1b4b27f73c74)
![image](https://github.com/user-attachments/assets/5d5c7af3-e077-48ad-a7ff-ad929643d0df)

This behavior is inconsistent and, in my opinion, qualifies as a bug. If deleting all columns is not allowed, the same restriction should apply when attempting to delete all columns at once, even when there are multiple columns. Alternatively, there could be an option similar to allowDeletingAllRows to handle this behavior explicitly.

I hope this clarification helps in addressing the issue.
