### ISSUE TITLE
contextmenu error

### ISSUE THREAD

**Issue by BasilSD** [paulhodel/jexcel#1675]
Hello,

I've been utilizing this library for nearly two years without encountering any issues. However, it has recently stopped functioning properly. The Excel sheet is no longer displaying, and upon debugging the jexcel.js file, I encountered the following error:  Uncaught TypeError: Cannot read properties of undefined (reading 'contextmenu')
![image](https://github.com/jspreadsheet/ce/assets/162311151/9e70d325-5f45-4126-9539-51a12698c7e2)

**Comment by hodeware** [comment]
This is when jSuites is not found. There might an error during import on jSuites.
