### ISSUE TITLE
Style is not being applied correctly.

### ISSUE THREAD

**Issue by kaushikd74** [paulhodel/jexcel#1676]
Hello,

I've been trying to import from XLSX, which has some styling. Whenever it was imported, it appeared that the styles were not properly applied. 
I'm using parser extension.
Could someone please assist me figure out how to solve this problem?

![Screenshot 2024-03-07 185211](https://github.com/jspreadsheet/ce/assets/113605006/d8d4aca6-2aac-4ded-ad55-b96f1da95833)

**Comment by paulorodalves** [comment]
It seems you need support on the Pro Version with the Enterprise extensions. Please can you contact support@jspreadsheet.com, with a sample of your file if is possible.

**Comment by kaushikd74** [comment]
However, we are using the pro version, and the identical problem appears on the jspreadsheet website as well.

**Comment by hodeware** [comment]
If you share the XLSX by email we can analyse and see if any changes are necessary to the parser. This channel is more for issues on CE.
