### ISSUE TITLE
wrong formula result : 10 + 1.12 = 11.120000000000001

### ISSUE THREAD

**Issue by mama3131** [paulhodel/jexcel#1683]
Hi,
is there a way to resolve the following wrong formula result :

A1 : "10"
B1 : "1.12"
C1 : "=A1+B1"

C1 will display 11.120000000000001 

same behaviour with 1.13 in B1 :
A1 : "10"
B1 : "1.13"
C1 : "=A1+B1"
C1 will display 11.129999999999999

Thx

**Comment by paulorodalves** [comment]
Precision is a JavaScript limitation and CE does not handle this.

Alternatively you can use Jspradsheet Pro with Formula Pro extension to handle that.

https://jspreadsheet.com/product/formulas


```
<html>
<script src="https://cdn.jsdelivr.net/npm/@jspreadsheet/formula-pro/dist/index.min.js"></script>
<script>
// Activate the precision adjust
formula.adjustPrecision = true;
// Define the license just once
formula.license('YjQzMzdlOTRiOGY3ZTQ0ZDQ4ZTI1YWU3MDFjMDI0ZWJmOTNjODA');
</script>
</html>
```

**Comment by mama3131** [comment]
@paulorodalves Thank you for your answer and your time.
