### ISSUE TITLE
Is there a way to jump to a particular row number?

### ISSUE THREAD

**Issue by asirota** [paulhodel/jexcel#1688]
Is there a way to jump to a certain row number via javascript? If given a row number can the spreadsheet be called to navigate to that row automatically?

**Comment by hodeware** [comment]
On the CE, you can navigate to a specific page (not a row). If you are using lazy loading, you can call instance.loadPage or instance.page if you are using pagination. There is also an option instance.goto(y, x) that can navigate to any cell on the spreadsheet, but this is only available in the Pro version.
