### ISSUE TITLE
How to disable undo (ctrl+z,) redo (ctrl+y) in version 10

### ISSUE THREAD

**Issue by aayushmb** [paulhodel/jexcel#1689]
I want to disable undo and redo feature in my spreadsheet (V10) but i couldn't find any implementation.

**Comment by paulorodalves** [comment]
That should work on version 10 (PRO)

`jspreadsheet.history.ignore = true;`

**Comment by aayushmb** [comment]
> That should work on version 10 (PRO)
> 
> `jspreadsheet.history.ignore = true;`



> That should work on version 10 (PRO)
> 
> `jspreadsheet.history.ignore = true;`

            Thanks, its working. Below is the code
            
            <Spreadsheet history = {( jspreadsheet.history.ignore = true )} />

**Comment by aayushmb** [comment]
> That should work on version 10 (PRO)
> 
> `jspreadsheet.history.ignore = true;`

Thanks, it's working. Below is the code how to implement

 <Spreadsheet history = {( jspreadsheet.history.ignore = true )}> 
       <TypedWorksheet />
 </Spreadsheet>
