### ISSUE TITLE
csvFileName: ,   csvHeaders: true, similarly can we restrict number of columns in downloaded excel

### ISSUE THREAD

**Issue by visalakshi88** [paulhodel/jexcel#1692]
In jexcel ,        $('#my-spreadsheet').jexcel('download');

csvFileName,   csvHeaders: , similarly can we restrict number of columns in downloaded excel

**Comment by hodeware** [comment]
Unfortunately that is not possible on the CE version. Using the Render XLSX (extension) you can use onbeforerender to modify the JSON that goes to the export, but that is only available on the PRO version. https://jspreadsheet.com/products/export-to-xlsx
