### ISSUE TITLE
Multiple Columns Filtering

### ISSUE THREAD

**Issue by lokkeshvp** [paulhodel/jexcel#1695]
I can't able to filter multiple columns at once, When I select on column filter the previous filter in other column get removed.

**Comment by IksanovRoman** [comment]
Yes, I had this problem too. It seems only in pro version it fixed.

**Comment by hodeware** [comment]
That is a limitation on the CE version. That is available on the PRO and there are no plans to include on the CE for this reason I will close this ticket.
