### ISSUE TITLE
Disable Calendar column type date picker and allow user to click icon to open the date picker.

### ISSUE THREAD

**Issue by inavnapro** [paulhodel/jexcel#1697]
Hello,

This is not an issue but more like a question. Is there a way to disable the calendar date picker popup and have input field with icon?  This way user can click the icon for the picker and input field is calendar type but allows user to type.  Please advise if there is a way or a solution to accomplish this requirement using jspeadsheet.  Thanks!

**Comment by hodeware** [comment]
Yes, you can create a custom editor (Custom column type).
https://bossanova.uk/jspreadsheet/v4/examples/column-types
