### ISSUE TITLE
Add new option from dropdown, without opening default browser alert/popup

### ISSUE THREAD

**Issue by VirendraMaheta7** [paulhodel/jexcel#1700]
I am using "type:dropdown" in jspreadsheet. While adding new option which is not available in dropdown source, it opens browser's default alert popup to enter new option.

Can we restrict that popup and insert new option directly from dropdown itself?

I am using Angular v14, and Jspreadsheet v10.5.3.

**Comment by hodeware** [comment]
You can use the prompt function which has been added.
