### ISSUE TITLE
Tabs and selection

### ISSUE THREAD

**Issue by brunoripa** [paulhodel/jexcel#1701]
Hi, I am rendering a multisheet workbook, and I have selection active. When selection is active, if I change tab and click on the sheet I have this:

```
TypeError: jexcel.current.resetSelection is not a function
```

Is this a bug or am I doing something wrong ? 

P.s.: I am clearly on the CE edition.

**Comment by hodeware** [comment]
This only exists when one spreadsheet is focused.
