### ISSUE TITLE
Is there a way to sort the filters?

### ISSUE THREAD

**Issue by JaredScar** [paulhodel/jexcel#1702]
I'm using jSpreadsheet in my application, but I've noticed that the filters when opening their dropdown have their options sorted in the order they show within the table at the current moment in time. Is there a way to sort it in order myself for every time it's opened?

As per example in the screenshot, I want the filters in here to be sorted numerically correctly. This works when I sort the column, but I want it to always be sorted. Is there an easy way to make this the case? Thanks!

![image](https://github.com/user-attachments/assets/7884210a-6673-4736-805e-c05ba7772089)

**Comment by hodeware** [comment]
This will be available next week on version 11.6.0 (only on the Professsinonal Version).
