### ISSUE TITLE
Type per cell

### ISSUE THREAD

**Issue by collmomo** [paulhodel/jexcel#1707]
Is there a way of doing this using the free version. The only way I'm currently thinking right now is adding a custom editor and having a separate variable that track types per cell and conditionally open/close/set/get every cell. The thing is that all my columns need to be my custom editor which would also require me to tweak the oninsertcolumn. I think that this method is somewhat too complicated, is there an easier way. Use case is like in excel. A column can have multiple ranges of different types. This is not a data table. Thanks

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by hodeware** [comment]
This is a feature of the PRO version.
