### ISSUE TITLE
columnDrag and rowDrag no longer seem to be working

### ISSUE THREAD

**Issue by sandzone** [paulhodel/jexcel#1709]
Clicking on column or row and dragging is not reordering rows/columns. It is just selecting multiple rows/columns.

Same behaviour can be observed even in the official example. Long click on any column and move the column - it just selects multiple columns.

https://bossanova.uk/jspreadsheet/v4/examples/column-dragging

**Comment by hodeware** [comment]
I have just tested and it is working as expected. Please send a video or more information, thanks.

**Comment by sandzone** [comment]
Hi,

Attached is a video about the issue. Please check and let me know.

Click + Drag did not work. Can you send a view of column and row dragging
in action?

Regards,
Sandeep

**Comment by hodeware** [comment]
![image](https://github.com/user-attachments/assets/28bb571a-1382-40c0-b00e-5fd4e2abed58)

![image](https://github.com/user-attachments/assets/bed10f76-c694-4af8-86c0-00152ff6a21d)

**Comment by hodeware** [comment]
Tested on Chrome and Firefox and it is working fine.

**Comment by hodeware** [comment]
Make sure you have on your declarations: `columnDrag: true`

**Comment by sandzone** [comment]
Is there a specific area in the column or the column header where I need to
click?

I am not seeing the triangle you have on Food column.

Regards,
Sandeep

**Comment by hodeware** [comment]
It will apper when you start the dragging. You you mouseover the lower border of the header, the cursor will change to indicate you can drag. But you need to enable that using `columnDrag: true`

**Comment by sandzone** [comment]
Thanks for this. It works.

I didn't know the activation region for the drag is lower half of the
header. I was just clicking on the header and trying to drag.

When I move the cursor to the lower half, I am able to drag the columns.
