### ISSUE TITLE
logo is downloaded from external URL http://bossanova.uk/jspreadsheet/logo.png

### ISSUE THREAD

**Issue by B-Truckses** [paulhodel/jexcel#1711]
On a webpage where everything is self-hosted, the JSpreadsheed - grid downloads a logo from the external URL **http://bossanova.uk/jspreadsheet/logo.png**

This is an issue in germany as you might get sued if you download assets like images, fonts etc. from an external url, regarding GDPR - see e.g.: https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/ )
No matter if this is reasonable or not or one might win or loose the court case, some customers has concerns about this and there are policies to self host anything in some companies.

In the following example we've downloaded the jspreadsheet-ce scripts and styles (and also the jsuites scripts and files) and hosted it on a local server:
[jspreadsheet.zip](https://github.com/user-attachments/files/17590812/jspreadsheet.zip)

```
<html>
    <head>
        <base href="/jspreadsheet/">
        <script src="./jsuites.js"></script>
        <script src="./jspreadsheet-ce.js"></script>
        <link rel="stylesheet" href="./jsuites.css" type="text/css" />
        <link rel="stylesheet" href="./jspreadsheet-ce.css" type="text/css" />
    </head>
    <body>
        <div id="my-spreadsheet"></div>

        <script>
var data = [
    ['Jazz', 'Honda', '2019-02-12', '', true, '$ 2.000,00', '#777700'],
    ['Civic', 'Honda', '2018-07-11', '', true, '$ 4.000,01', '#007777'],
];

jspreadsheet(document.getElementById('my-spreadsheet'), {
    data:data,
    columns: [
        { type: 'text', title:'Car', width:120 },
        { type: 'dropdown', title:'Make', width:200, source:[ "Alfa Romeo", "Audi", "Bmw" ] },
        { type: 'calendar', title:'Available', width:200 },
        { type: 'image', title:'Photo', width:120 },
        { type: 'checkbox', title:'Stock', width:80 },
        { type: 'numeric', title:'Price', width:100, mask:'$ #.##,00', decimal:',' },
        { type: 'color', width:100, render:'square', }
    ]
});
        </script>
    </body>
</html>
```

Opening the devtools and watching the network tab we see http-calls to **http://bossanova.uk/jspreadsheet/logo.png**
![image](https://github.com/user-attachments/assets/b7a87cbc-2fd9-4c24-9549-5b272918083a)

The problem occures in **https://github.com/jspreadsheet/ce/blob/master/src/index.js** in **line 697 & 698**:
```
var img = document.createElement('img');
img.src = '//bossanova.uk/jspreadsheet/logo.png';
```

The problem is that img - elements don't need to be added to the DOM to fire a download - as soon as you assign something to the `src` property of an image, the browser tries to download it no matter if it's part of the current DOM or not. So a possible workaround to remove the image from the DOM after calling `jspreadsheet(...)` is not working as the browser already downloaded the image.

**Comment by hodeware** [comment]
Thanks. The img has been removed from the package, you can upgrade to v4.15.0

**Comment by B-Truckses** [comment]
wow - that was fast 👍  
thanks
