### ISSUE TITLE
Dynamically sets the read-only properties of columns

### ISSUE THREAD

**Issue by 372798735** [paulhodel/jexcel#1712]
How do I dynamically set the read-only properties of a column, as shown in the following figure：
![Snipaste_2024-11-14_10-57-11](https://github.com/user-attachments/assets/ea6ca0c5-c806-46eb-82d0-f8004272bd7a)

**Comment by hodeware** [comment]
`worksheetInstance.records[0][1].classList.add('readonly'); // For B1`
