### ISSUE TITLE
I am unable to run it under Modal.

### ISSUE THREAD

**Issue by Teolone88** [paulhodel/jexcel#1713]
The modal, once opened, does not load the library.
**Js**
```
document.addEventListener('DOMContentLoaded', function () {
    // Initialize JSpreadsheet
    var spreadsheet = jspreadsheet(document.getElementById('spreadsheet-container'), {
        data: [
            ['Example 1', 'Example 2'],
            ['Example 3', 'Example 4']
        ],
        columns: [
            { type: 'text', title: 'Column 1', width: 120 },
            { type: 'text', title: 'Column 2', width: 120 }
        ],
    });

    // Handle row insertion
    document.getElementById('insert-row').addEventListener('click', function () {
        // Insert a new blank row at the end
        spreadsheet.insertRow([], spreadsheet.getData().length);
        
        // Alternatively, to insert at a specific index, specify the index:
        // spreadsheet.insertRow([], 1); // Inserts a row at index 1 (second position)
        
        alert('New row inserted!');
    });
});
```
**Html**
`<div id="spreadsheet"></div>`

The outcome is an empty modal.
The libraries are loaded but the jexcel or jspreadsheet are not recognized.

Not sure what is the problem.

**Comment by hodeware** [comment]
You might need to create Jspreadsheet only when the modal IS opened and the DOM is visible. I believe there are erros on the calculations since JS will return 0 since the elements inside the modal are hidden.

**Comment by Teolone88** [comment]
I have decided to discard the modal way. However, I am trying to add
dynamic selection of cells during formula building, in case the cell value
starts with =.
I have managed to add a Ctrl+click to individually click the cells and add
the reference but I am unable to add the range in case the click is not up.
The latter does not work. Would you have any advice on where I should look
into the library to achieve this behavior?

**Comment by hodeware** [comment]
I am not sure if I understood your question. To avoid mix the questions, I am closing this ticket about the Modal. Please fell free to send another one.
