### ISSUE TITLE
Text Wrap error

### ISSUE THREAD

**Issue by Davewp196** [paulhodel/jexcel#281]
I've just looked at your example of text wrapping https://bossanova.uk/jexcel/examples/text-wrapping, and it appears the text is not being wrapped, and is being truncated.  

Rather than setting the cell style to be "white-space:pre", I think it should be "white-space:pre-wrap" as given in https://www.w3schools.com/cssref/pr_text_white-space.asp

**Comment by paulhodel** [comment]
Yes, you are right. I have changed the project, but this will be available only in the next release.
