### ISSUE TITLE
Change settings

### ISSUE THREAD

**Issue by PragnaBrahmbhatt** [paulhodel/jexcel#284]
Hello, 
How to change below settings after adding JExcel.
`allowInsertRow:false,`
`allowManualInsertRow:false,`
`allowInsertColumn:false,`
`allowManualInsertColumn:false,`
`allowDeleteRow:false,`
`allowDeleteColumn:false,`
 For example I am adding JExcel with data and on scroll, I am adding some more rows inside table.
But I am not allowing any function of insert,update,delete,right click. 
Because of this the rows are not inserted on scroll. 
So my question is that: Is there any function so I can change the settings pragmatically?

**Comment by pphod** [comment]
In the just release new version 2.0.0 you can find this feature:
$('#my').jexcel('setConfig', 'allowInsertRow', true);
